/// Flutter icons CustomIcons
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomIcons
///      fonts:
///       - asset: fonts/CustomIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class CustomIcons {
  CustomIcons._();

  static const _kFontFam = 'CustomIcons';
  static const String? _kFontPkg = null;

  static const IconData cancel = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData setting = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData status = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData information = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chart = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData about = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
