// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'dongle.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

Dongle _$DongleFromJson(Map<String, dynamic> json) => Dongle(
      alignChannel1: json['d_0'] as int? ?? 2,
      alignChannelMode1: json['d_1'] as int? ?? 1,
      alignChannel2: json['d_2'] as int? ?? 2,
      alignChannelMode2: json['d_3'] as int? ?? 1,
      sdleTGCCableLength: json['1_0'] as int? ?? 9,
      sdleSplitOption: json['1_1'] as int? ?? 1,
      sdlePilotFrequencyMode: json['1_2'] as int? ?? 0,
      sdleAGCMode: json['1_3'] as int? ?? 1,
      sdleALCMode: json['1_4'] as int? ?? 1,
      sdleFirstChannelLoadingFrequency: json['1_5'] as int? ?? 258,
      sdleLastChannelLoadingFrequency: json['1_6'] as int? ?? 1794,
      sdleFirstChannelLoadingLevel: json['1_7'] as int? ?? 340,
      sdleLastChannelLoadingLevel: json['1_8'] as int? ?? 511,
      sdlePilotFrequency1: json['1_9'] as int? ?? 330,
      sdlePilotFrequency2: json['1_10'] as int? ?? 1785,
      sdleDSVVA1: json['1_11'] as int? ?? 0,
      sdleDSSlope1: json['1_12'] as int? ?? 60,
      sdleUSVCA2: json['1_13'] as int? ?? 40,
      sdleEREQ: json['1_14'] as int? ?? 30,
      sdleUSVCA1: json['1_15'] as int? ?? 0,
      bleTGCCableLength: json['2_0'] as int? ?? 9,
      bleSplitOption: json['2_1'] as int? ?? 1,
      blePilotFrequencyMode: json['2_2'] as int? ?? 0,
      bleAGCMode: json['2_3'] as int? ?? 1,
      bleALCMode: json['2_4'] as int? ?? 1,
      bleFirstChannelLoadingFrequency: json['2_5'] as int? ?? 258,
      bleLastChannelLoadingFrequency: json['2_6'] as int? ?? 1794,
      bleFirstChannelLoadingLevel: json['2_7'] as int? ?? 340,
      bleLastChannelLoadingLevel: json['2_8'] as int? ?? 511,
      blePilotFrequency1: json['2_9'] as int? ?? 330,
      blePilotFrequency2: json['2_10'] as int? ?? 1785,
      bleDSVVA1: json['2_11'] as int? ?? 0,
      bleDSSlope1: json['2_12'] as int? ?? 60,
      bleUSVCA2: json['2_13'] as int? ?? 40,
      bleEREQ: json['2_14'] as int? ?? 30,
      bleUSVCA1: json['2_15'] as int? ?? 0,
      mbTGCCableLength: json['3_0'] as int? ?? 9,
      mbSplitOption: json['3_1'] as int? ?? 1,
      mbPilotFrequencyMode: json['3_2'] as int? ?? 0,
      mbAGCMode: json['3_3'] as int? ?? 1,
      mbALCMode: json['3_4'] as int? ?? 1,
      mbFirstChannelLoadingFrequency: json['3_5'] as int? ?? 258,
      mbLastChannelLoadingFrequency: json['3_6'] as int? ?? 1794,
      mbFirstChannelLoadingLevel: json['3_7'] as int? ?? 340,
      mbLastChannelLoadingLevel: json['3_8'] as int? ?? 511,
      mbPilotFrequency1: json['3_9'] as int? ?? 330,
      mbPilotFrequency2: json['3_10'] as int? ?? 1785,
      mbDSVVA1: json['3_11'] as int? ?? 0,
      mbDSSlope1: json['3_12'] as int? ?? 0,
      mbUSVCA2: json['3_13'] as int? ?? 60,
      mbEREQ: json['3_14'] as int? ?? 0,
      mbDSVVA4: json['3_15'] as int? ?? 15,
      mbUSVCA1: json['3_16'] as int? ?? 0,
      mbUSVCA3: json['3_17'] as int? ?? 0,
      mbUSVCA4: json['3_18'] as int? ?? 0,
      nodeSplitOption: json['4_0'] as int? ?? 1,
      nodeDSVVA1: json['4_1'] as int? ?? 0,
      nodeDSInSlope1: json['4_2'] as int? ?? 0,
      nodeUSVCA1: json['4_3'] as int? ?? 0,
      nodeDSVVA3: json['4_4'] as int? ?? 0,
      nodeDSInSlope3: json['4_5'] as int? ?? 0,
      nodeUSVCA3: json['4_6'] as int? ?? 0,
      nodeDSVVA4: json['4_7'] as int? ?? 0,
      nodeDSInSlope4: json['4_8'] as int? ?? 0,
      nodeUSVCA4: json['4_9'] as int? ?? 0,
      nodeDSVVA6: json['4_10'] as int? ?? 0,
      nodeDSInSlope6: json['4_11'] as int? ?? 0,
      nodeUSVCA6: json['4_12'] as int? ?? 0,
      trTGCCableLength: json['5_0'] as int? ?? 9,
      trSplitOption: json['5_1'] as int? ?? 1,
      trPilotFrequencyMode: json['5_2'] as int? ?? 0,
      trAGCMode: json['5_3'] as int? ?? 1,
      trALCMode: json['5_4'] as int? ?? 1,
      trFirstChannelLoadingFrequency: json['5_5'] as int? ?? 258,
      trLastChannelLoadingFrequency: json['5_6'] as int? ?? 1794,
      trFirstChannelLoadingLevel: json['5_7'] as int? ?? 340,
      trLastChannelLoadingLevel: json['5_8'] as int? ?? 511,
      trPilotFrequency1: json['5_9'] as int? ?? 330,
      trPilotFrequency2: json['5_10'] as int? ?? 1785,
      trDSVVA1: json['5_11'] as int? ?? 10,
      trDSSlope1: json['5_12'] as int? ?? 30,
      trUSVCA2: json['5_13'] as int? ?? 50,
      trEREQ: json['5_14'] as int? ?? 40,
      trDSVVA4: json['5_15'] as int? ?? 15,
      trDSVVA5: json['5_16'] as int? ?? 0,
      trDSSlope3: json['5_17'] as int? ?? 0,
      trDSSlope4: json['5_18'] as int? ?? 0,
      trUSVCA1: json['5_19'] as int? ?? 0,
      trUSVCA3: json['5_20'] as int? ?? 0,
      trUSVCA4: json['5_21'] as int? ?? 0,
      brTGCCableLength: json['6_0'] as int? ?? 9,
      brSplitOption: json['6_1'] as int? ?? 1,
      brPilotFrequencyMode: json['6_2'] as int? ?? 0,
      brAGCMode: json['6_3'] as int? ?? 1,
      brALCMode: json['6_4'] as int? ?? 1,
      brFirstChannelLoadingFrequency: json['6_5'] as int? ?? 258,
      brLastChannelLoadingFrequency: json['6_6'] as int? ?? 1794,
      brFirstChannelLoadingLevel: json['6_7'] as int? ?? 340,
      brLastChannelLoadingLevel: json['6_8'] as int? ?? 511,
      brPilotFrequency1: json['6_9'] as int? ?? 330,
      brPilotFrequency2: json['6_10'] as int? ?? 1785,
      brDSVVA1: json['6_11'] as int? ?? 10,
      brDSSlope1: json['6_12'] as int? ?? 30,
      brUSVCA2: json['6_13'] as int? ?? 50,
      brEREQ: json['6_14'] as int? ?? 40,
      brDSVVA4: json['6_15'] as int? ?? 15,
      brDSSlope3: json['6_16'] as int? ?? 0,
      brUSVCA3: json['6_17'] as int? ?? 0,
      brUSVCA4: json['6_18'] as int? ?? 0,
      leTGCCableLength: json['7_0'] as int? ?? 9,
      leSplitOption: json['7_1'] as int? ?? 1,
      lePilotFrequencyMode: json['7_2'] as int? ?? 0,
      leAGCMode: json['7_3'] as int? ?? 1,
      leALCMode: json['7_4'] as int? ?? 1,
      leFirstChannelLoadingFrequency: json['7_5'] as int? ?? 258,
      leLastChannelLoadingFrequency: json['7_6'] as int? ?? 1794,
      leFirstChannelLoadingLevel: json['7_7'] as int? ?? 340,
      leLastChannelLoadingLevel: json['7_8'] as int? ?? 511,
      lePilotFrequency1: json['7_9'] as int? ?? 330,
      lePilotFrequency2: json['7_10'] as int? ?? 1785,
      leDSVVA1: json['7_11'] as int? ?? 0,
      leDSSlope1: json['7_12'] as int? ?? 60,
      leUSVCA2: json['7_13'] as int? ?? 75,
      leEREQ: json['7_14'] as int? ?? 0,
      leUSVCA1: json['7_15'] as int? ?? 0,
    );

Map<String, dynamic> _$DongleToJson(Dongle instance) => <String, dynamic>{
      'd_0': instance.alignChannel1,
      'd_1': instance.alignChannelMode1,
      'd_2': instance.alignChannel2,
      'd_3': instance.alignChannelMode2,
      '1_0': instance.sdleTGCCableLength,
      '1_1': instance.sdleSplitOption,
      '1_2': instance.sdlePilotFrequencyMode,
      '1_3': instance.sdleAGCMode,
      '1_4': instance.sdleALCMode,
      '1_5': instance.sdleFirstChannelLoadingFrequency,
      '1_6': instance.sdleLastChannelLoadingFrequency,
      '1_7': instance.sdleFirstChannelLoadingLevel,
      '1_8': instance.sdleLastChannelLoadingLevel,
      '1_9': instance.sdlePilotFrequency1,
      '1_10': instance.sdlePilotFrequency2,
      '1_11': instance.sdleDSVVA1,
      '1_12': instance.sdleDSSlope1,
      '1_13': instance.sdleUSVCA2,
      '1_14': instance.sdleEREQ,
      '1_15': instance.sdleUSVCA1,
      '2_0': instance.bleTGCCableLength,
      '2_1': instance.bleSplitOption,
      '2_2': instance.blePilotFrequencyMode,
      '2_3': instance.bleAGCMode,
      '2_4': instance.bleALCMode,
      '2_5': instance.bleFirstChannelLoadingFrequency,
      '2_6': instance.bleLastChannelLoadingFrequency,
      '2_7': instance.bleFirstChannelLoadingLevel,
      '2_8': instance.bleLastChannelLoadingLevel,
      '2_9': instance.blePilotFrequency1,
      '2_10': instance.blePilotFrequency2,
      '2_11': instance.bleDSVVA1,
      '2_12': instance.bleDSSlope1,
      '2_13': instance.bleUSVCA2,
      '2_14': instance.bleEREQ,
      '2_15': instance.bleUSVCA1,
      '3_0': instance.mbTGCCableLength,
      '3_1': instance.mbSplitOption,
      '3_2': instance.mbPilotFrequencyMode,
      '3_3': instance.mbAGCMode,
      '3_4': instance.mbALCMode,
      '3_5': instance.mbFirstChannelLoadingFrequency,
      '3_6': instance.mbLastChannelLoadingFrequency,
      '3_7': instance.mbFirstChannelLoadingLevel,
      '3_8': instance.mbLastChannelLoadingLevel,
      '3_9': instance.mbPilotFrequency1,
      '3_10': instance.mbPilotFrequency2,
      '3_11': instance.mbDSVVA1,
      '3_12': instance.mbDSSlope1,
      '3_13': instance.mbUSVCA2,
      '3_14': instance.mbEREQ,
      '3_15': instance.mbDSVVA4,
      '3_16': instance.mbUSVCA1,
      '3_17': instance.mbUSVCA3,
      '3_18': instance.mbUSVCA4,
      '4_0': instance.nodeSplitOption,
      '4_1': instance.nodeDSVVA1,
      '4_2': instance.nodeDSInSlope1,
      '4_3': instance.nodeUSVCA1,
      '4_4': instance.nodeDSVVA3,
      '4_5': instance.nodeDSInSlope3,
      '4_6': instance.nodeUSVCA3,
      '4_7': instance.nodeDSVVA4,
      '4_8': instance.nodeDSInSlope4,
      '4_9': instance.nodeUSVCA4,
      '4_10': instance.nodeDSVVA6,
      '4_11': instance.nodeDSInSlope6,
      '4_12': instance.nodeUSVCA6,
      '5_0': instance.trTGCCableLength,
      '5_1': instance.trSplitOption,
      '5_2': instance.trPilotFrequencyMode,
      '5_3': instance.trAGCMode,
      '5_4': instance.trALCMode,
      '5_5': instance.trFirstChannelLoadingFrequency,
      '5_6': instance.trLastChannelLoadingFrequency,
      '5_7': instance.trFirstChannelLoadingLevel,
      '5_8': instance.trLastChannelLoadingLevel,
      '5_9': instance.trPilotFrequency1,
      '5_10': instance.trPilotFrequency2,
      '5_11': instance.trDSVVA1,
      '5_12': instance.trDSSlope1,
      '5_13': instance.trUSVCA2,
      '5_14': instance.trEREQ,
      '5_15': instance.trDSVVA4,
      '5_16': instance.trDSVVA5,
      '5_17': instance.trDSSlope3,
      '5_18': instance.trDSSlope4,
      '5_19': instance.trUSVCA1,
      '5_20': instance.trUSVCA3,
      '5_21': instance.trUSVCA4,
      '6_0': instance.brTGCCableLength,
      '6_1': instance.brSplitOption,
      '6_2': instance.brPilotFrequencyMode,
      '6_3': instance.brAGCMode,
      '6_4': instance.brALCMode,
      '6_5': instance.brFirstChannelLoadingFrequency,
      '6_6': instance.brLastChannelLoadingFrequency,
      '6_7': instance.brFirstChannelLoadingLevel,
      '6_8': instance.brLastChannelLoadingLevel,
      '6_9': instance.brPilotFrequency1,
      '6_10': instance.brPilotFrequency2,
      '6_11': instance.brDSVVA1,
      '6_12': instance.brDSSlope1,
      '6_13': instance.brUSVCA2,
      '6_14': instance.brEREQ,
      '6_15': instance.brDSVVA4,
      '6_16': instance.brDSSlope3,
      '6_17': instance.brUSVCA3,
      '6_18': instance.brUSVCA4,
      '7_0': instance.leTGCCableLength,
      '7_1': instance.leSplitOption,
      '7_2': instance.lePilotFrequencyMode,
      '7_3': instance.leAGCMode,
      '7_4': instance.leALCMode,
      '7_5': instance.leFirstChannelLoadingFrequency,
      '7_6': instance.leLastChannelLoadingFrequency,
      '7_7': instance.leFirstChannelLoadingLevel,
      '7_8': instance.leLastChannelLoadingLevel,
      '7_9': instance.lePilotFrequency1,
      '7_10': instance.lePilotFrequency2,
      '7_11': instance.leDSVVA1,
      '7_12': instance.leDSSlope1,
      '7_13': instance.leUSVCA2,
      '7_14': instance.leEREQ,
      '7_15': instance.leUSVCA1,
    };
