import 'package:aci_plus_app/core/data_key.dart';

class ControlItemValue {
  static Map<String, Map<String, List<Map<DataKey, MinMax>>>>
      allValueCollections = {
    '1.8': valueCollection,
    '1.2': valueCollection1P2G,
  };

  static Map<String, List<Map<DataKey, MinMax>>> valueCollection = {
    '1': [
      // 204/258
      // MFTJ
      {},
      // SDLE
      {
        DataKey.dsVVA1: const MinMax(min: 0.0, max: 13.0),
        DataKey.dsSlope1: const MinMax(min: 0.0, max: 10.0),
        DataKey.usVCA2: const MinMax(min: 0.0, max: 15.0),
        DataKey.eREQ: const MinMax(min: 0.0, max: 15.0),
        DataKey.usVCA1: const MinMax(min: 0.0, max: 29.0),
        // DataKey.ingressSetting2,
      },
      // Moto BLE
      {
        DataKey.dsVVA1: const MinMax(min: 0.0, max: 13.0),
        DataKey.dsSlope1: const MinMax(min: 0.0, max: 10.0),
        DataKey.usVCA2: const MinMax(min: 0.0, max: 15.0),
        DataKey.eREQ: const MinMax(min: 0.0, max: 15.0),
        DataKey.usVCA1: const MinMax(min: 0.0, max: 29.0),
        // DataKey.ingressSetting2,
      },
      // Moto MB
      {
        DataKey.dsVVA1: const MinMax(min: 0.0, max: 13.0),
        DataKey.dsSlope1: const MinMax(min: 0.0, max: 10.0),
        DataKey.dsVVA4: const MinMax(min: 0.0, max: 10.0),
        DataKey.usVCA2: const MinMax(min: 0.0, max: 15.0),
        DataKey.eREQ: const MinMax(min: 0.0, max: 15.0),
        DataKey.usVCA1: const MinMax(min: 0.0, max: 29.0),
        DataKey.usVCA3: const MinMax(min: 0.0, max: 29.0),
        DataKey.usVCA4: const MinMax(min: 0.0, max: 29.0),
        //  DataKey.ingressSetting2,
        //  DataKey.ingressSetting3,
        //  DataKey.ingressSetting4,
      },
      // C-Cor Node
      {
        DataKey.dsVVA1: const MinMax(min: 0.0, max: 25.0),
        DataKey.dsVVA3: const MinMax(min: 0.0, max: 25.0),
        DataKey.dsVVA4: const MinMax(min: 0.0, max: 25.0),
        DataKey.dsVVA6: const MinMax(min: 0.0, max: 25.0),
        DataKey.dsOutSlope1: const MinMax(min: 0.0, max: 8.0),
        DataKey.dsOutSlope3: const MinMax(min: 0.0, max: 8.0),
        DataKey.dsOutSlope4: const MinMax(min: 0.0, max: 8.0),
        DataKey.dsOutSlope6: const MinMax(min: 0.0, max: 8.0),
        DataKey.biasCurrent1: const MinMax(min: 320, max: 520),
        DataKey.biasCurrent3: const MinMax(min: 320, max: 520),
        DataKey.biasCurrent4: const MinMax(min: 320, max: 520),
        DataKey.biasCurrent6: const MinMax(min: 320, max: 520),
        DataKey.usVCA1: const MinMax(min: 0.0, max: 25.0),
        DataKey.usVCA3: const MinMax(min: 0.0, max: 25.0),
        DataKey.usVCA4: const MinMax(min: 0.0, max: 25.0),
        DataKey.usVCA6: const MinMax(min: 0.0, max: 25.0),
        // DataKey.ingressSetting1,
        // DataKey.ingressSetting3,
        // DataKey.ingressSetting4,
        // DataKey.ingressSetting6,
      },
      {
        // C-Cor TR
        DataKey.dsVVA1: const MinMax(min: 0.0, max: 13.0),
        DataKey.dsSlope1: const MinMax(min: 0.0, max: 10.0),
        DataKey.dsVVA4: const MinMax(min: 0.0, max: 10.0),
        DataKey.dsVVA5: const MinMax(min: 0.0, max: 10.0),
        DataKey.dsSlope3: const MinMax(min: 0.0, max: 10.0),
        DataKey.dsSlope4: const MinMax(min: 0.0, max: 10.0),
        DataKey.usVCA2: const MinMax(min: 0.0, max: 15.0),
        DataKey.eREQ: const MinMax(min: 0.0, max: 15.0),
        DataKey.usVCA1: const MinMax(min: 0.0, max: 29.0),
        DataKey.usVCA3: const MinMax(min: 0.0, max: 29.0),
        DataKey.usVCA4: const MinMax(min: 0.0, max: 29.0),
        // DataKey.ingressSetting2,
        // DataKey.ingressSetting3,
        // DataKey.ingressSetting4,
      },
      {
        // C-Cor BR
        DataKey.dsVVA1: const MinMax(min: 0.0, max: 13.0),
        DataKey.dsSlope1: const MinMax(min: 0.0, max: 10.0),
        DataKey.dsVVA4: const MinMax(min: 0.0, max: 10.0),
        DataKey.dsSlope3: const MinMax(min: 0.0, max: 10.0),
        DataKey.dsSlope4: const MinMax(min: 0.0, max: 10.0),
        DataKey.usVCA2: const MinMax(min: 0.0, max: 15.0),
        DataKey.eREQ: const MinMax(min: 0.0, max: 15.0),
        DataKey.usVCA3: const MinMax(min: 0.0, max: 29.0),
        DataKey.usVCA4: const MinMax(min: 0.0, max: 29.0),
        // DataKey.ingressSetting3,
        // DataKey.ingressSetting4,
      },
      {
        // C-Cor LE
        DataKey.dsVVA1: const MinMax(min: 0.0, max: 13.0),
        DataKey.dsSlope1: const MinMax(min: 0.0, max: 10.0),
        DataKey.usVCA2: const MinMax(min: 0.0, max: 15.0),
        DataKey.eREQ: const MinMax(min: 0.0, max: 15.0),
        DataKey.usVCA1: const MinMax(min: 0.0, max: 29.0),
        // SettingControl.returnIngressSetting2: DataKey.ingressSetting2,
      },
      {
        // SDAT
        DataKey.dsVVA1: const MinMax(min: 0.0, max: 13.0),
        DataKey.dsSlope1: const MinMax(min: 0.0, max: 10.0),
        DataKey.dsVVA4: const MinMax(min: 0.0, max: 10.0),
        DataKey.dsVVA5: const MinMax(min: 0.0, max: 10.0),
        DataKey.dsSlope3: const MinMax(min: 0.0, max: 10.0),
        DataKey.dsSlope4: const MinMax(min: 0.0, max: 10.0),
        DataKey.usVCA2: const MinMax(min: 0.0, max: 15.0),
        DataKey.eREQ: const MinMax(min: 0.0, max: 15.0),
        DataKey.usVCA1: const MinMax(min: 0.0, max: 29.0),
        DataKey.usVCA3: const MinMax(min: 0.0, max: 29.0),
        DataKey.usVCA4: const MinMax(min: 0.0, max: 29.0),
        //  DataKey.ingressSetting2,
        //  DataKey.ingressSetting3,
        //  DataKey.ingressSetting4,
      },
      {
        // SDAM
        DataKey.dsVVA1: const MinMax(min: 0.0, max: 13.0),
        DataKey.dsSlope1: const MinMax(min: 0.0, max: 10.0),
        DataKey.dsVVA4: const MinMax(min: 0.0, max: 10.0),
        DataKey.usVCA2: const MinMax(min: 0.0, max: 15.0),
        DataKey.eREQ: const MinMax(min: 0.0, max: 15.0),
        DataKey.usVCA1: const MinMax(min: 0.0, max: 29.0),
        DataKey.usVCA3: const MinMax(min: 0.0, max: 29.0),
        DataKey.usVCA4: const MinMax(min: 0.0, max: 29.0),
        // DataKey.ingressSetting2,
        // DataKey.ingressSetting3,
        // DataKey.ingressSetting4,
      },
    ],
    '2': [
      // 300/372
      // MFTJ
      {},
      // SDLE
      {
        DataKey.dsVVA1: const MinMax(min: 0.0, max: 13.0),
        DataKey.dsSlope1: const MinMax(min: 0.0, max: 10.0),
        DataKey.usVCA2: const MinMax(min: 0.0, max: 15.0),
        DataKey.eREQ: const MinMax(min: 0.0, max: 15.0),
        DataKey.usVCA1: const MinMax(min: 0.0, max: 29.0),
        // DataKey.ingressSetting2,
      },
      // Moto BLE
      {
        DataKey.dsVVA1: const MinMax(min: 0.0, max: 13.0),
        DataKey.dsSlope1: const MinMax(min: 0.0, max: 10.0),
        DataKey.usVCA2: const MinMax(min: 0.0, max: 15.0),
        DataKey.eREQ: const MinMax(min: 0.0, max: 15.0),
        DataKey.usVCA1: const MinMax(min: 0.0, max: 29.0),
        // DataKey.ingressSetting2,
      },
      // Moto MB
      {
        DataKey.dsVVA1: const MinMax(min: 0.0, max: 13.0),
        DataKey.dsSlope1: const MinMax(min: 0.0, max: 10.0),
        DataKey.dsVVA4: const MinMax(min: 0.0, max: 10.0),
        DataKey.usVCA2: const MinMax(min: 0.0, max: 15.0),
        DataKey.eREQ: const MinMax(min: 0.0, max: 15.0),
        DataKey.usVCA1: const MinMax(min: 0.0, max: 29.0),
        DataKey.usVCA3: const MinMax(min: 0.0, max: 29.0),
        DataKey.usVCA4: const MinMax(min: 0.0, max: 29.0),
        //  DataKey.ingressSetting2,
        //  DataKey.ingressSetting3,
        //  DataKey.ingressSetting4,
      },
      // C-Cor Node
      {
        DataKey.dsVVA1: const MinMax(min: 0.0, max: 25.0),
        DataKey.dsVVA3: const MinMax(min: 0.0, max: 25.0),
        DataKey.dsVVA4: const MinMax(min: 0.0, max: 25.0),
        DataKey.dsVVA6: const MinMax(min: 0.0, max: 25.0),
        DataKey.dsOutSlope1: const MinMax(min: 0.0, max: 8.0),
        DataKey.dsOutSlope3: const MinMax(min: 0.0, max: 8.0),
        DataKey.dsOutSlope4: const MinMax(min: 0.0, max: 8.0),
        DataKey.dsOutSlope6: const MinMax(min: 0.0, max: 8.0),
        DataKey.biasCurrent1: const MinMax(min: 320, max: 520),
        DataKey.biasCurrent3: const MinMax(min: 320, max: 520),
        DataKey.biasCurrent4: const MinMax(min: 320, max: 520),
        DataKey.biasCurrent6: const MinMax(min: 320, max: 520),
        DataKey.usVCA1: const MinMax(min: 0.0, max: 25.0),
        DataKey.usVCA3: const MinMax(min: 0.0, max: 25.0),
        DataKey.usVCA4: const MinMax(min: 0.0, max: 25.0),
        DataKey.usVCA6: const MinMax(min: 0.0, max: 25.0),
        // DataKey.ingressSetting1,
        // DataKey.ingressSetting3,
        // DataKey.ingressSetting4,
        // DataKey.ingressSetting6,
      },
      {
        // C-Cor TR
        DataKey.dsVVA1: const MinMax(min: 0.0, max: 13.0),
        DataKey.dsSlope1: const MinMax(min: 0.0, max: 10.0),
        DataKey.dsVVA4: const MinMax(min: 0.0, max: 10.0),
        DataKey.dsVVA5: const MinMax(min: 0.0, max: 10.0),
        DataKey.dsSlope3: const MinMax(min: 0.0, max: 10.0),
        DataKey.dsSlope4: const MinMax(min: 0.0, max: 10.0),
        DataKey.usVCA2: const MinMax(min: 0.0, max: 15.0),
        DataKey.eREQ: const MinMax(min: 0.0, max: 15.0),
        DataKey.usVCA1: const MinMax(min: 0.0, max: 29.0),
        DataKey.usVCA3: const MinMax(min: 0.0, max: 29.0),
        DataKey.usVCA4: const MinMax(min: 0.0, max: 29.0),
        // DataKey.ingressSetting2,
        // DataKey.ingressSetting3,
        // DataKey.ingressSetting4,
      },
      {
        // C-Cor BR
        DataKey.dsVVA1: const MinMax(min: 0.0, max: 13.0),
        DataKey.dsSlope1: const MinMax(min: 0.0, max: 10.0),
        DataKey.dsVVA4: const MinMax(min: 0.0, max: 10.0),
        DataKey.dsSlope3: const MinMax(min: 0.0, max: 10.0),
        DataKey.dsSlope4: const MinMax(min: 0.0, max: 10.0),
        DataKey.usVCA2: const MinMax(min: 0.0, max: 15.0),
        DataKey.eREQ: const MinMax(min: 0.0, max: 15.0),
        DataKey.usVCA3: const MinMax(min: 0.0, max: 29.0),
        DataKey.usVCA4: const MinMax(min: 0.0, max: 29.0),
        // DataKey.ingressSetting3,
        // DataKey.ingressSetting4,
      },
      {
        // C-Cor LE
        DataKey.dsVVA1: const MinMax(min: 0.0, max: 13.0),
        DataKey.dsSlope1: const MinMax(min: 0.0, max: 10.0),
        DataKey.usVCA2: const MinMax(min: 0.0, max: 15.0),
        DataKey.eREQ: const MinMax(min: 0.0, max: 15.0),
        DataKey.usVCA1: const MinMax(min: 0.0, max: 29.0),
        // SettingControl.returnIngressSetting2: DataKey.ingressSetting2,
      },
      {
        // SDAT
        DataKey.dsVVA1: const MinMax(min: 0.0, max: 13.0),
        DataKey.dsSlope1: const MinMax(min: 0.0, max: 10.0),
        DataKey.dsVVA4: const MinMax(min: 0.0, max: 10.0),
        DataKey.dsVVA5: const MinMax(min: 0.0, max: 10.0),
        DataKey.dsSlope3: const MinMax(min: 0.0, max: 10.0),
        DataKey.dsSlope4: const MinMax(min: 0.0, max: 10.0),
        DataKey.usVCA2: const MinMax(min: 0.0, max: 15.0),
        DataKey.eREQ: const MinMax(min: 0.0, max: 15.0),
        DataKey.usVCA1: const MinMax(min: 0.0, max: 29.0),
        DataKey.usVCA3: const MinMax(min: 0.0, max: 29.0),
        DataKey.usVCA4: const MinMax(min: 0.0, max: 29.0),
        //  DataKey.ingressSetting2,
        //  DataKey.ingressSetting3,
        //  DataKey.ingressSetting4,
      },
      {
        // SDAM
        DataKey.dsVVA1: const MinMax(min: 0.0, max: 13.0),
        DataKey.dsSlope1: const MinMax(min: 0.0, max: 10.0),
        DataKey.dsVVA4: const MinMax(min: 0.0, max: 10.0),
        DataKey.usVCA2: const MinMax(min: 0.0, max: 15.0),
        DataKey.eREQ: const MinMax(min: 0.0, max: 15.0),
        DataKey.usVCA1: const MinMax(min: 0.0, max: 29.0),
        DataKey.usVCA3: const MinMax(min: 0.0, max: 29.0),
        DataKey.usVCA4: const MinMax(min: 0.0, max: 29.0),
        // DataKey.ingressSetting2,
        // DataKey.ingressSetting3,
        // DataKey.ingressSetting4,
      },
    ],
    '3': [
      // 396/492
      // MFTJ
      {},
      // SDLE
      {
        DataKey.dsVVA1: const MinMax(min: 0.0, max: 13.0),
        DataKey.dsSlope1: const MinMax(min: 0.0, max: 10.0),
        DataKey.usVCA2: const MinMax(min: 0.0, max: 15.0),
        DataKey.eREQ: const MinMax(min: 0.0, max: 15.0),
        DataKey.usVCA1: const MinMax(min: 0.0, max: 29.0),
        // DataKey.ingressSetting2,
      },
      // Moto BLE
      {
        DataKey.dsVVA1: const MinMax(min: 0.0, max: 13.0),
        DataKey.dsSlope1: const MinMax(min: 0.0, max: 10.0),
        DataKey.usVCA2: const MinMax(min: 0.0, max: 15.0),
        DataKey.eREQ: const MinMax(min: 0.0, max: 15.0),
        DataKey.usVCA1: const MinMax(min: 0.0, max: 29.0),
        // DataKey.ingressSetting2,
      },
      // Moto MB
      {
        DataKey.dsVVA1: const MinMax(min: 0.0, max: 13.0),
        DataKey.dsSlope1: const MinMax(min: 0.0, max: 10.0),
        DataKey.dsVVA4: const MinMax(min: 0.0, max: 10.0),
        DataKey.usVCA2: const MinMax(min: 0.0, max: 15.0),
        DataKey.eREQ: const MinMax(min: 0.0, max: 15.0),
        DataKey.usVCA1: const MinMax(min: 0.0, max: 29.0),
        DataKey.usVCA3: const MinMax(min: 0.0, max: 29.0),
        DataKey.usVCA4: const MinMax(min: 0.0, max: 29.0),
        //  DataKey.ingressSetting2,
        //  DataKey.ingressSetting3,
        //  DataKey.ingressSetting4,
      },
      // C-Cor Node
      {
        DataKey.dsVVA1: const MinMax(min: 0.0, max: 25.0),
        DataKey.dsVVA3: const MinMax(min: 0.0, max: 25.0),
        DataKey.dsVVA4: const MinMax(min: 0.0, max: 25.0),
        DataKey.dsVVA6: const MinMax(min: 0.0, max: 25.0),
        DataKey.dsOutSlope1: const MinMax(min: 0.0, max: 8.0),
        DataKey.dsOutSlope3: const MinMax(min: 0.0, max: 8.0),
        DataKey.dsOutSlope4: const MinMax(min: 0.0, max: 8.0),
        DataKey.dsOutSlope6: const MinMax(min: 0.0, max: 8.0),
        DataKey.biasCurrent1: const MinMax(min: 320, max: 520),
        DataKey.biasCurrent3: const MinMax(min: 320, max: 520),
        DataKey.biasCurrent4: const MinMax(min: 320, max: 520),
        DataKey.biasCurrent6: const MinMax(min: 320, max: 520),
        DataKey.usVCA1: const MinMax(min: 0.0, max: 25.0),
        DataKey.usVCA3: const MinMax(min: 0.0, max: 25.0),
        DataKey.usVCA4: const MinMax(min: 0.0, max: 25.0),
        DataKey.usVCA6: const MinMax(min: 0.0, max: 25.0),
        // DataKey.ingressSetting1,
        // DataKey.ingressSetting3,
        // DataKey.ingressSetting4,
        // DataKey.ingressSetting6,
      },
      {
        // C-Cor TR
        DataKey.dsVVA1: const MinMax(min: 0.0, max: 13.0),
        DataKey.dsSlope1: const MinMax(min: 0.0, max: 10.0),
        DataKey.dsVVA4: const MinMax(min: 0.0, max: 10.0),
        DataKey.dsVVA5: const MinMax(min: 0.0, max: 10.0),
        DataKey.dsSlope3: const MinMax(min: 0.0, max: 10.0),
        DataKey.dsSlope4: const MinMax(min: 0.0, max: 10.0),
        DataKey.usVCA2: const MinMax(min: 0.0, max: 15.0),
        DataKey.eREQ: const MinMax(min: 0.0, max: 15.0),
        DataKey.usVCA1: const MinMax(min: 0.0, max: 29.0),
        DataKey.usVCA3: const MinMax(min: 0.0, max: 29.0),
        DataKey.usVCA4: const MinMax(min: 0.0, max: 29.0),
        // DataKey.ingressSetting2,
        // DataKey.ingressSetting3,
        // DataKey.ingressSetting4,
      },
      {
        // C-Cor BR
        DataKey.dsVVA1: const MinMax(min: 0.0, max: 13.0),
        DataKey.dsSlope1: const MinMax(min: 0.0, max: 10.0),
        DataKey.dsVVA4: const MinMax(min: 0.0, max: 10.0),
        DataKey.dsSlope3: const MinMax(min: 0.0, max: 10.0),
        DataKey.dsSlope4: const MinMax(min: 0.0, max: 10.0),
        DataKey.usVCA2: const MinMax(min: 0.0, max: 15.0),
        DataKey.eREQ: const MinMax(min: 0.0, max: 15.0),
        DataKey.usVCA3: const MinMax(min: 0.0, max: 29.0),
        DataKey.usVCA4: const MinMax(min: 0.0, max: 29.0),
        // DataKey.ingressSetting3,
        // DataKey.ingressSetting4,
      },
      {
        // C-Cor LE
        DataKey.dsVVA1: const MinMax(min: 0.0, max: 13.0),
        DataKey.dsSlope1: const MinMax(min: 0.0, max: 10.0),
        DataKey.usVCA2: const MinMax(min: 0.0, max: 15.0),
        DataKey.eREQ: const MinMax(min: 0.0, max: 15.0),
        DataKey.usVCA1: const MinMax(min: 0.0, max: 29.0),
        // SettingControl.returnIngressSetting2: DataKey.ingressSetting2,
      },
      {
        // SDAT
        DataKey.dsVVA1: const MinMax(min: 0.0, max: 13.0),
        DataKey.dsSlope1: const MinMax(min: 0.0, max: 10.0),
        DataKey.dsVVA4: const MinMax(min: 0.0, max: 10.0),
        DataKey.dsVVA5: const MinMax(min: 0.0, max: 10.0),
        DataKey.dsSlope3: const MinMax(min: 0.0, max: 10.0),
        DataKey.dsSlope4: const MinMax(min: 0.0, max: 10.0),
        DataKey.usVCA2: const MinMax(min: 0.0, max: 15.0),
        DataKey.eREQ: const MinMax(min: 0.0, max: 15.0),
        DataKey.usVCA1: const MinMax(min: 0.0, max: 29.0),
        DataKey.usVCA3: const MinMax(min: 0.0, max: 29.0),
        DataKey.usVCA4: const MinMax(min: 0.0, max: 29.0),
        //  DataKey.ingressSetting2,
        //  DataKey.ingressSetting3,
        //  DataKey.ingressSetting4,
      },
      {
        // SDAM
        DataKey.dsVVA1: const MinMax(min: 0.0, max: 13.0),
        DataKey.dsSlope1: const MinMax(min: 0.0, max: 10.0),
        DataKey.dsVVA4: const MinMax(min: 0.0, max: 10.0),
        DataKey.usVCA2: const MinMax(min: 0.0, max: 15.0),
        DataKey.eREQ: const MinMax(min: 0.0, max: 15.0),
        DataKey.usVCA1: const MinMax(min: 0.0, max: 29.0),
        DataKey.usVCA3: const MinMax(min: 0.0, max: 29.0),
        DataKey.usVCA4: const MinMax(min: 0.0, max: 29.0),
        // DataKey.ingressSetting2,
        // DataKey.ingressSetting3,
        // DataKey.ingressSetting4,
      },
    ],
    '4': [
      // 492/606
      // MFTJ
      {},
      // SDLE
      {
        DataKey.dsVVA1: const MinMax(min: 0.0, max: 13.0),
        DataKey.dsSlope1: const MinMax(min: 0.0, max: 10.0),
        DataKey.usVCA2: const MinMax(min: 0.0, max: 15.0),
        DataKey.eREQ: const MinMax(min: 0.0, max: 15.0),
        DataKey.usVCA1: const MinMax(min: 0.0, max: 29.0),
        // DataKey.ingressSetting2,
      },
      // Moto BLE
      {
        DataKey.dsVVA1: const MinMax(min: 0.0, max: 13.0),
        DataKey.dsSlope1: const MinMax(min: 0.0, max: 10.0),
        DataKey.usVCA2: const MinMax(min: 0.0, max: 15.0),
        DataKey.eREQ: const MinMax(min: 0.0, max: 15.0),
        DataKey.usVCA1: const MinMax(min: 0.0, max: 29.0),
        // DataKey.ingressSetting2,
      },
      // Moto MB
      {
        DataKey.dsVVA1: const MinMax(min: 0.0, max: 13.0),
        DataKey.dsSlope1: const MinMax(min: 0.0, max: 10.0),
        DataKey.dsVVA4: const MinMax(min: 0.0, max: 10.0),
        DataKey.usVCA2: const MinMax(min: 0.0, max: 15.0),
        DataKey.eREQ: const MinMax(min: 0.0, max: 15.0),
        DataKey.usVCA1: const MinMax(min: 0.0, max: 29.0),
        DataKey.usVCA3: const MinMax(min: 0.0, max: 29.0),
        DataKey.usVCA4: const MinMax(min: 0.0, max: 29.0),
        //  DataKey.ingressSetting2,
        //  DataKey.ingressSetting3,
        //  DataKey.ingressSetting4,
      },
      // C-Cor Node
      {
        DataKey.dsVVA1: const MinMax(min: 0.0, max: 25.0),
        DataKey.dsVVA3: const MinMax(min: 0.0, max: 25.0),
        DataKey.dsVVA4: const MinMax(min: 0.0, max: 25.0),
        DataKey.dsVVA6: const MinMax(min: 0.0, max: 25.0),
        DataKey.dsOutSlope1: const MinMax(min: 0.0, max: 8.0),
        DataKey.dsOutSlope3: const MinMax(min: 0.0, max: 8.0),
        DataKey.dsOutSlope4: const MinMax(min: 0.0, max: 8.0),
        DataKey.dsOutSlope6: const MinMax(min: 0.0, max: 8.0),
        DataKey.biasCurrent1: const MinMax(min: 320, max: 520),
        DataKey.biasCurrent3: const MinMax(min: 320, max: 520),
        DataKey.biasCurrent4: const MinMax(min: 320, max: 520),
        DataKey.biasCurrent6: const MinMax(min: 320, max: 520),
        DataKey.usVCA1: const MinMax(min: 0.0, max: 25.0),
        DataKey.usVCA3: const MinMax(min: 0.0, max: 25.0),
        DataKey.usVCA4: const MinMax(min: 0.0, max: 25.0),
        DataKey.usVCA6: const MinMax(min: 0.0, max: 25.0),
        // DataKey.ingressSetting1,
        // DataKey.ingressSetting3,
        // DataKey.ingressSetting4,
        // DataKey.ingressSetting6,
      },
      {
        // C-Cor TR
        DataKey.dsVVA1: const MinMax(min: 0.0, max: 13.0),
        DataKey.dsSlope1: const MinMax(min: 0.0, max: 10.0),
        DataKey.dsVVA4: const MinMax(min: 0.0, max: 10.0),
        DataKey.dsVVA5: const MinMax(min: 0.0, max: 10.0),
        DataKey.dsSlope3: const MinMax(min: 0.0, max: 10.0),
        DataKey.dsSlope4: const MinMax(min: 0.0, max: 10.0),
        DataKey.usVCA2: const MinMax(min: 0.0, max: 15.0),
        DataKey.eREQ: const MinMax(min: 0.0, max: 15.0),
        DataKey.usVCA1: const MinMax(min: 0.0, max: 29.0),
        DataKey.usVCA3: const MinMax(min: 0.0, max: 29.0),
        DataKey.usVCA4: const MinMax(min: 0.0, max: 29.0),
        // DataKey.ingressSetting2,
        // DataKey.ingressSetting3,
        // DataKey.ingressSetting4,
      },
      {
        // C-Cor BR
        DataKey.dsVVA1: const MinMax(min: 0.0, max: 13.0),
        DataKey.dsSlope1: const MinMax(min: 0.0, max: 10.0),
        DataKey.dsVVA4: const MinMax(min: 0.0, max: 10.0),
        DataKey.dsSlope3: const MinMax(min: 0.0, max: 10.0),
        DataKey.dsSlope4: const MinMax(min: 0.0, max: 10.0),
        DataKey.usVCA2: const MinMax(min: 0.0, max: 15.0),
        DataKey.eREQ: const MinMax(min: 0.0, max: 15.0),
        DataKey.usVCA3: const MinMax(min: 0.0, max: 29.0),
        DataKey.usVCA4: const MinMax(min: 0.0, max: 29.0),
        // DataKey.ingressSetting3,
        // DataKey.ingressSetting4,
      },
      {
        // C-Cor LE
        DataKey.dsVVA1: const MinMax(min: 0.0, max: 13.0),
        DataKey.dsSlope1: const MinMax(min: 0.0, max: 10.0),
        DataKey.usVCA2: const MinMax(min: 0.0, max: 15.0),
        DataKey.eREQ: const MinMax(min: 0.0, max: 15.0),
        DataKey.usVCA1: const MinMax(min: 0.0, max: 29.0),
        // SettingControl.returnIngressSetting2: DataKey.ingressSetting2,
      },
      {
        // SDAT
        DataKey.dsVVA1: const MinMax(min: 0.0, max: 13.0),
        DataKey.dsSlope1: const MinMax(min: 0.0, max: 10.0),
        DataKey.dsVVA4: const MinMax(min: 0.0, max: 10.0),
        DataKey.dsVVA5: const MinMax(min: 0.0, max: 10.0),
        DataKey.dsSlope3: const MinMax(min: 0.0, max: 10.0),
        DataKey.dsSlope4: const MinMax(min: 0.0, max: 10.0),
        DataKey.usVCA2: const MinMax(min: 0.0, max: 15.0),
        DataKey.eREQ: const MinMax(min: 0.0, max: 15.0),
        DataKey.usVCA1: const MinMax(min: 0.0, max: 29.0),
        DataKey.usVCA3: const MinMax(min: 0.0, max: 29.0),
        DataKey.usVCA4: const MinMax(min: 0.0, max: 29.0),
        //  DataKey.ingressSetting2,
        //  DataKey.ingressSetting3,
        //  DataKey.ingressSetting4,
      },
      {
        // SDAM
        DataKey.dsVVA1: const MinMax(min: 0.0, max: 13.0),
        DataKey.dsSlope1: const MinMax(min: 0.0, max: 10.0),
        DataKey.dsVVA4: const MinMax(min: 0.0, max: 10.0),
        DataKey.usVCA2: const MinMax(min: 0.0, max: 15.0),
        DataKey.eREQ: const MinMax(min: 0.0, max: 15.0),
        DataKey.usVCA1: const MinMax(min: 0.0, max: 29.0),
        DataKey.usVCA3: const MinMax(min: 0.0, max: 29.0),
        DataKey.usVCA4: const MinMax(min: 0.0, max: 29.0),
        // DataKey.ingressSetting2,
        // DataKey.ingressSetting3,
        // DataKey.ingressSetting4,
      },
    ],
    '5': [
      // 684/834
      // MFTJ
      {},
      // SDLE
      {
        DataKey.dsVVA1: const MinMax(min: 0.0, max: 13.0),
        DataKey.dsSlope1: const MinMax(min: 0.0, max: 10.0),
        DataKey.usVCA2: const MinMax(min: 0.0, max: 15.0),
        DataKey.eREQ: const MinMax(min: 0.0, max: 15.0),
        DataKey.usVCA1: const MinMax(min: 0.0, max: 29.0),
        // DataKey.ingressSetting2,
      },
      // Moto BLE
      {
        DataKey.dsVVA1: const MinMax(min: 0.0, max: 13.0),
        DataKey.dsSlope1: const MinMax(min: 0.0, max: 10.0),
        DataKey.usVCA2: const MinMax(min: 0.0, max: 15.0),
        DataKey.eREQ: const MinMax(min: 0.0, max: 15.0),
        DataKey.usVCA1: const MinMax(min: 0.0, max: 29.0),
        // DataKey.ingressSetting2,
      },
      // Moto MB
      {
        DataKey.dsVVA1: const MinMax(min: 0.0, max: 13.0),
        DataKey.dsSlope1: const MinMax(min: 0.0, max: 10.0),
        DataKey.dsVVA4: const MinMax(min: 0.0, max: 10.0),
        DataKey.usVCA2: const MinMax(min: 0.0, max: 15.0),
        DataKey.eREQ: const MinMax(min: 0.0, max: 15.0),
        DataKey.usVCA1: const MinMax(min: 0.0, max: 29.0),
        DataKey.usVCA3: const MinMax(min: 0.0, max: 29.0),
        DataKey.usVCA4: const MinMax(min: 0.0, max: 29.0),
        //  DataKey.ingressSetting2,
        //  DataKey.ingressSetting3,
        //  DataKey.ingressSetting4,
      },
      // C-Cor Node
      {
        DataKey.dsVVA1: const MinMax(min: 0.0, max: 25.0),
        DataKey.dsVVA3: const MinMax(min: 0.0, max: 25.0),
        DataKey.dsVVA4: const MinMax(min: 0.0, max: 25.0),
        DataKey.dsVVA6: const MinMax(min: 0.0, max: 25.0),
        DataKey.dsOutSlope1: const MinMax(min: 0.0, max: 8.0),
        DataKey.dsOutSlope3: const MinMax(min: 0.0, max: 8.0),
        DataKey.dsOutSlope4: const MinMax(min: 0.0, max: 8.0),
        DataKey.dsOutSlope6: const MinMax(min: 0.0, max: 8.0),
        DataKey.biasCurrent1: const MinMax(min: 320, max: 520),
        DataKey.biasCurrent3: const MinMax(min: 320, max: 520),
        DataKey.biasCurrent4: const MinMax(min: 320, max: 520),
        DataKey.biasCurrent6: const MinMax(min: 320, max: 520),
        DataKey.usVCA1: const MinMax(min: 0.0, max: 25.0),
        DataKey.usVCA3: const MinMax(min: 0.0, max: 25.0),
        DataKey.usVCA4: const MinMax(min: 0.0, max: 25.0),
        DataKey.usVCA6: const MinMax(min: 0.0, max: 25.0),
        // DataKey.ingressSetting1,
        // DataKey.ingressSetting3,
        // DataKey.ingressSetting4,
        // DataKey.ingressSetting6,
      },
      {
        // C-Cor TR
        DataKey.dsVVA1: const MinMax(min: 0.0, max: 13.0),
        DataKey.dsSlope1: const MinMax(min: 0.0, max: 10.0),
        DataKey.dsVVA4: const MinMax(min: 0.0, max: 10.0),
        DataKey.dsVVA5: const MinMax(min: 0.0, max: 10.0),
        DataKey.dsSlope3: const MinMax(min: 0.0, max: 10.0),
        DataKey.dsSlope4: const MinMax(min: 0.0, max: 10.0),
        DataKey.usVCA2: const MinMax(min: 0.0, max: 15.0),
        DataKey.eREQ: const MinMax(min: 0.0, max: 15.0),
        DataKey.usVCA1: const MinMax(min: 0.0, max: 29.0),
        DataKey.usVCA3: const MinMax(min: 0.0, max: 29.0),
        DataKey.usVCA4: const MinMax(min: 0.0, max: 29.0),
        // DataKey.ingressSetting2,
        // DataKey.ingressSetting3,
        // DataKey.ingressSetting4,
      },
      {
        // C-Cor BR
        DataKey.dsVVA1: const MinMax(min: 0.0, max: 13.0),
        DataKey.dsSlope1: const MinMax(min: 0.0, max: 10.0),
        DataKey.dsVVA4: const MinMax(min: 0.0, max: 10.0),
        DataKey.dsSlope3: const MinMax(min: 0.0, max: 10.0),
        DataKey.dsSlope4: const MinMax(min: 0.0, max: 10.0),
        DataKey.usVCA2: const MinMax(min: 0.0, max: 15.0),
        DataKey.eREQ: const MinMax(min: 0.0, max: 15.0),
        DataKey.usVCA3: const MinMax(min: 0.0, max: 29.0),
        DataKey.usVCA4: const MinMax(min: 0.0, max: 29.0),
        // DataKey.ingressSetting3,
        // DataKey.ingressSetting4,
      },
      {
        // C-Cor LE
        DataKey.dsVVA1: const MinMax(min: 0.0, max: 13.0),
        DataKey.dsSlope1: const MinMax(min: 0.0, max: 10.0),
        DataKey.usVCA2: const MinMax(min: 0.0, max: 15.0),
        DataKey.eREQ: const MinMax(min: 0.0, max: 15.0),
        DataKey.usVCA1: const MinMax(min: 0.0, max: 29.0),
        // SettingControl.returnIngressSetting2: DataKey.ingressSetting2,
      },
      {
        // SDAT
        DataKey.dsVVA1: const MinMax(min: 0.0, max: 13.0),
        DataKey.dsSlope1: const MinMax(min: 0.0, max: 10.0),
        DataKey.dsVVA4: const MinMax(min: 0.0, max: 10.0),
        DataKey.dsVVA5: const MinMax(min: 0.0, max: 10.0),
        DataKey.dsSlope3: const MinMax(min: 0.0, max: 10.0),
        DataKey.dsSlope4: const MinMax(min: 0.0, max: 10.0),
        DataKey.usVCA2: const MinMax(min: 0.0, max: 15.0),
        DataKey.eREQ: const MinMax(min: 0.0, max: 15.0),
        DataKey.usVCA1: const MinMax(min: 0.0, max: 29.0),
        DataKey.usVCA3: const MinMax(min: 0.0, max: 29.0),
        DataKey.usVCA4: const MinMax(min: 0.0, max: 29.0),
        //  DataKey.ingressSetting2,
        //  DataKey.ingressSetting3,
        //  DataKey.ingressSetting4,
      },
      {
        // SDAM
        DataKey.dsVVA1: const MinMax(min: 0.0, max: 13.0),
        DataKey.dsSlope1: const MinMax(min: 0.0, max: 10.0),
        DataKey.dsVVA4: const MinMax(min: 0.0, max: 10.0),
        DataKey.usVCA2: const MinMax(min: 0.0, max: 15.0),
        DataKey.eREQ: const MinMax(min: 0.0, max: 15.0),
        DataKey.usVCA1: const MinMax(min: 0.0, max: 29.0),
        DataKey.usVCA3: const MinMax(min: 0.0, max: 29.0),
        DataKey.usVCA4: const MinMax(min: 0.0, max: 29.0),
        // DataKey.ingressSetting2,
        // DataKey.ingressSetting3,
        // DataKey.ingressSetting4,
      },
    ],
    '6': [
      // 85/105
      // MFTJ
      {},
      // SDLE
      {
        DataKey.dsVVA1: const MinMax(min: 0.0, max: 13.0),
        DataKey.dsSlope1: const MinMax(min: 0.0, max: 10.0),
        DataKey.usVCA2: const MinMax(min: 0.0, max: 15.0),
        DataKey.eREQ: const MinMax(min: 0.0, max: 15.0),
        DataKey.usVCA1: const MinMax(min: 0.0, max: 29.0),
        // DataKey.ingressSetting2,
      },
      // Moto BLE
      {
        DataKey.dsVVA1: const MinMax(min: 0.0, max: 13.0),
        DataKey.dsSlope1: const MinMax(min: 0.0, max: 10.0),
        DataKey.usVCA2: const MinMax(min: 0.0, max: 15.0),
        DataKey.eREQ: const MinMax(min: 0.0, max: 15.0),
        DataKey.usVCA1: const MinMax(min: 0.0, max: 29.0),
        // DataKey.ingressSetting2,
      },
      // Moto MB
      {
        DataKey.dsVVA1: const MinMax(min: 0.0, max: 13.0),
        DataKey.dsSlope1: const MinMax(min: 0.0, max: 10.0),
        DataKey.dsVVA4: const MinMax(min: 0.0, max: 10.0),
        DataKey.usVCA2: const MinMax(min: 0.0, max: 15.0),
        DataKey.eREQ: const MinMax(min: 0.0, max: 15.0),
        DataKey.usVCA1: const MinMax(min: 0.0, max: 29.0),
        DataKey.usVCA3: const MinMax(min: 0.0, max: 29.0),
        DataKey.usVCA4: const MinMax(min: 0.0, max: 29.0),
        //  DataKey.ingressSetting2,
        //  DataKey.ingressSetting3,
        //  DataKey.ingressSetting4,
      },
      // C-Cor Node
      {
        DataKey.dsVVA1: const MinMax(min: 0.0, max: 25.0),
        DataKey.dsVVA3: const MinMax(min: 0.0, max: 25.0),
        DataKey.dsVVA4: const MinMax(min: 0.0, max: 25.0),
        DataKey.dsVVA6: const MinMax(min: 0.0, max: 25.0),
        DataKey.dsOutSlope1: const MinMax(min: 0.0, max: 8.0),
        DataKey.dsOutSlope3: const MinMax(min: 0.0, max: 8.0),
        DataKey.dsOutSlope4: const MinMax(min: 0.0, max: 8.0),
        DataKey.dsOutSlope6: const MinMax(min: 0.0, max: 8.0),
        DataKey.biasCurrent1: const MinMax(min: 320, max: 520),
        DataKey.biasCurrent3: const MinMax(min: 320, max: 520),
        DataKey.biasCurrent4: const MinMax(min: 320, max: 520),
        DataKey.biasCurrent6: const MinMax(min: 320, max: 520),
        DataKey.usVCA1: const MinMax(min: 0.0, max: 25.0),
        DataKey.usVCA3: const MinMax(min: 0.0, max: 25.0),
        DataKey.usVCA4: const MinMax(min: 0.0, max: 25.0),
        DataKey.usVCA6: const MinMax(min: 0.0, max: 25.0),
        // DataKey.ingressSetting1,
        // DataKey.ingressSetting3,
        // DataKey.ingressSetting4,
        // DataKey.ingressSetting6,
      },
      {
        // C-Cor TR
        DataKey.dsVVA1: const MinMax(min: 0.0, max: 13.0),
        DataKey.dsSlope1: const MinMax(min: 0.0, max: 10.0),
        DataKey.dsVVA4: const MinMax(min: 0.0, max: 10.0),
        DataKey.dsVVA5: const MinMax(min: 0.0, max: 10.0),
        DataKey.dsSlope3: const MinMax(min: 0.0, max: 10.0),
        DataKey.dsSlope4: const MinMax(min: 0.0, max: 10.0),
        DataKey.usVCA2: const MinMax(min: 0.0, max: 15.0),
        DataKey.eREQ: const MinMax(min: 0.0, max: 15.0),
        DataKey.usVCA1: const MinMax(min: 0.0, max: 29.0),
        DataKey.usVCA3: const MinMax(min: 0.0, max: 29.0),
        DataKey.usVCA4: const MinMax(min: 0.0, max: 29.0),
        // DataKey.ingressSetting2,
        // DataKey.ingressSetting3,
        // DataKey.ingressSetting4,
      },
      {
        // C-Cor BR
        DataKey.dsVVA1: const MinMax(min: 0.0, max: 13.0),
        DataKey.dsSlope1: const MinMax(min: 0.0, max: 10.0),
        DataKey.dsVVA4: const MinMax(min: 0.0, max: 10.0),
        DataKey.dsSlope3: const MinMax(min: 0.0, max: 10.0),
        DataKey.dsSlope4: const MinMax(min: 0.0, max: 10.0),
        DataKey.usVCA2: const MinMax(min: 0.0, max: 15.0),
        DataKey.eREQ: const MinMax(min: 0.0, max: 15.0),
        DataKey.usVCA3: const MinMax(min: 0.0, max: 29.0),
        DataKey.usVCA4: const MinMax(min: 0.0, max: 29.0),
        // DataKey.ingressSetting3,
        // DataKey.ingressSetting4,
      },
      {
        // C-Cor LE
        DataKey.dsVVA1: const MinMax(min: 0.0, max: 13.0),
        DataKey.dsSlope1: const MinMax(min: 0.0, max: 10.0),
        DataKey.usVCA2: const MinMax(min: 0.0, max: 15.0),
        DataKey.eREQ: const MinMax(min: 0.0, max: 15.0),
        DataKey.usVCA1: const MinMax(min: 0.0, max: 29.0),
        // SettingControl.returnIngressSetting2: DataKey.ingressSetting2,
      },
      {
        // SDAT
        DataKey.dsVVA1: const MinMax(min: 0.0, max: 13.0),
        DataKey.dsSlope1: const MinMax(min: 0.0, max: 10.0),
        DataKey.dsVVA4: const MinMax(min: 0.0, max: 10.0),
        DataKey.dsVVA5: const MinMax(min: 0.0, max: 10.0),
        DataKey.dsSlope3: const MinMax(min: 0.0, max: 10.0),
        DataKey.dsSlope4: const MinMax(min: 0.0, max: 10.0),
        DataKey.usVCA2: const MinMax(min: 0.0, max: 15.0),
        DataKey.eREQ: const MinMax(min: 0.0, max: 15.0),
        DataKey.usVCA1: const MinMax(min: 0.0, max: 29.0),
        DataKey.usVCA3: const MinMax(min: 0.0, max: 29.0),
        DataKey.usVCA4: const MinMax(min: 0.0, max: 29.0),
        //  DataKey.ingressSetting2,
        //  DataKey.ingressSetting3,
        //  DataKey.ingressSetting4,
      },
      {
        // SDAM
        DataKey.dsVVA1: const MinMax(min: 0.0, max: 13.0),
        DataKey.dsSlope1: const MinMax(min: 0.0, max: 10.0),
        DataKey.dsVVA4: const MinMax(min: 0.0, max: 10.0),
        DataKey.usVCA2: const MinMax(min: 0.0, max: 15.0),
        DataKey.eREQ: const MinMax(min: 0.0, max: 15.0),
        DataKey.usVCA1: const MinMax(min: 0.0, max: 29.0),
        DataKey.usVCA3: const MinMax(min: 0.0, max: 29.0),
        DataKey.usVCA4: const MinMax(min: 0.0, max: 29.0),
        // DataKey.ingressSetting2,
        // DataKey.ingressSetting3,
        // DataKey.ingressSetting4,
      },
    ],
  };

  static Map<String, List<Map<DataKey, MinMax>>> valueCollection1P2G = {
    '1': [
      // 204/258
      // MFTJ
      {},
      // SDLE
      {
        DataKey.dsVVA1: const MinMax(min: 0.0, max: 20.0),
        DataKey.dsSlope1: const MinMax(min: 0.0, max: 10.0),
        DataKey.usVCA2: const MinMax(min: 0.0, max: 15.0),
        DataKey.eREQ: const MinMax(min: 0.0, max: 15.0),
        DataKey.usVCA1: const MinMax(min: 0.0, max: 29.0),
        // DataKey.ingressSetting2,
      },
      // Moto BLE
      {
        DataKey.dsVVA1: const MinMax(min: 0.0, max: 20.0),
        DataKey.dsSlope1: const MinMax(min: 0.0, max: 10.0),
        DataKey.usVCA2: const MinMax(min: 0.0, max: 15.0),
        DataKey.eREQ: const MinMax(min: 0.0, max: 15.0),
        DataKey.usVCA1: const MinMax(min: 0.0, max: 29.0),
        // DataKey.ingressSetting2,
      },
      // Moto MB
      {
        DataKey.dsVVA1: const MinMax(min: 0.0, max: 20.0),
        DataKey.dsSlope1: const MinMax(min: 0.0, max: 10.0),
        DataKey.dsVVA4: const MinMax(min: 0.0, max: 10.0),
        DataKey.usVCA2: const MinMax(min: 0.0, max: 15.0),
        DataKey.eREQ: const MinMax(min: 0.0, max: 15.0),
        DataKey.usVCA1: const MinMax(min: 0.0, max: 29.0),
        DataKey.usVCA3: const MinMax(min: 0.0, max: 29.0),
        DataKey.usVCA4: const MinMax(min: 0.0, max: 29.0),
        //  DataKey.ingressSetting2,
        //  DataKey.ingressSetting3,
        //  DataKey.ingressSetting4,
      },
      // C-Cor Node
      {
        DataKey.dsVVA1: const MinMax(min: 0.0, max: 25.0),
        DataKey.dsVVA3: const MinMax(min: 0.0, max: 25.0),
        DataKey.dsVVA4: const MinMax(min: 0.0, max: 25.0),
        DataKey.dsVVA6: const MinMax(min: 0.0, max: 25.0),
        DataKey.dsOutSlope1: const MinMax(min: 0.0, max: 8.0),
        DataKey.dsOutSlope3: const MinMax(min: 0.0, max: 8.0),
        DataKey.dsOutSlope4: const MinMax(min: 0.0, max: 8.0),
        DataKey.dsOutSlope6: const MinMax(min: 0.0, max: 8.0),
        DataKey.biasCurrent1: const MinMax(min: 320, max: 520),
        DataKey.biasCurrent3: const MinMax(min: 320, max: 520),
        DataKey.biasCurrent4: const MinMax(min: 320, max: 520),
        DataKey.biasCurrent6: const MinMax(min: 320, max: 520),
        DataKey.usVCA1: const MinMax(min: 0.0, max: 25.0),
        DataKey.usVCA3: const MinMax(min: 0.0, max: 25.0),
        DataKey.usVCA4: const MinMax(min: 0.0, max: 25.0),
        DataKey.usVCA6: const MinMax(min: 0.0, max: 25.0),
        // DataKey.ingressSetting1,
        // DataKey.ingressSetting3,
        // DataKey.ingressSetting4,
        // DataKey.ingressSetting6,
      },
      {
        // C-Cor TR
        DataKey.dsVVA1: const MinMax(min: 0.0, max: 20.0),
        DataKey.dsSlope1: const MinMax(min: 0.0, max: 10.0),
        DataKey.dsVVA4: const MinMax(min: 0.0, max: 10.0),
        DataKey.dsVVA5: const MinMax(min: 0.0, max: 10.0),
        DataKey.dsSlope3: const MinMax(min: 0.0, max: 10.0),
        DataKey.dsSlope4: const MinMax(min: 0.0, max: 10.0),
        DataKey.usVCA2: const MinMax(min: 0.0, max: 15.0),
        DataKey.eREQ: const MinMax(min: 0.0, max: 15.0),
        DataKey.usVCA1: const MinMax(min: 0.0, max: 29.0),
        DataKey.usVCA3: const MinMax(min: 0.0, max: 29.0),
        DataKey.usVCA4: const MinMax(min: 0.0, max: 29.0),
        // DataKey.ingressSetting2,
        // DataKey.ingressSetting3,
        // DataKey.ingressSetting4,
      },
      {
        // C-Cor BR
        DataKey.dsVVA1: const MinMax(min: 0.0, max: 20.0),
        DataKey.dsSlope1: const MinMax(min: 0.0, max: 10.0),
        DataKey.dsVVA4: const MinMax(min: 0.0, max: 10.0),
        DataKey.dsSlope3: const MinMax(min: 0.0, max: 10.0),
        DataKey.dsSlope4: const MinMax(min: 0.0, max: 10.0),
        DataKey.usVCA2: const MinMax(min: 0.0, max: 15.0),
        DataKey.eREQ: const MinMax(min: 0.0, max: 15.0),
        DataKey.usVCA3: const MinMax(min: 0.0, max: 29.0),
        DataKey.usVCA4: const MinMax(min: 0.0, max: 29.0),
        // DataKey.ingressSetting3,
        // DataKey.ingressSetting4,
      },
      {
        // C-Cor LE
        DataKey.dsVVA1: const MinMax(min: 0.0, max: 20.0),
        DataKey.dsSlope1: const MinMax(min: 0.0, max: 10.0),
        DataKey.usVCA2: const MinMax(min: 0.0, max: 15.0),
        DataKey.eREQ: const MinMax(min: 0.0, max: 15.0),
        DataKey.usVCA1: const MinMax(min: 0.0, max: 29.0),
        // SettingControl.returnIngressSetting2: DataKey.ingressSetting2,
      },
      {
        // SDAT
        DataKey.dsVVA1: const MinMax(min: 0.0, max: 20.0),
        DataKey.dsSlope1: const MinMax(min: 0.0, max: 10.0),
        DataKey.dsVVA4: const MinMax(min: 0.0, max: 10.0),
        DataKey.dsVVA5: const MinMax(min: 0.0, max: 10.0),
        DataKey.dsSlope3: const MinMax(min: 0.0, max: 10.0),
        DataKey.dsSlope4: const MinMax(min: 0.0, max: 10.0),
        DataKey.usVCA2: const MinMax(min: 0.0, max: 15.0),
        DataKey.eREQ: const MinMax(min: 0.0, max: 15.0),
        DataKey.usVCA1: const MinMax(min: 0.0, max: 29.0),
        DataKey.usVCA3: const MinMax(min: 0.0, max: 29.0),
        DataKey.usVCA4: const MinMax(min: 0.0, max: 29.0),
        //  DataKey.ingressSetting2,
        //  DataKey.ingressSetting3,
        //  DataKey.ingressSetting4,
      },
      {
        // SDAM
        DataKey.dsVVA1: const MinMax(min: 0.0, max: 20.0),
        DataKey.dsSlope1: const MinMax(min: 0.0, max: 10.0),
        DataKey.dsVVA4: const MinMax(min: 0.0, max: 10.0),
        DataKey.usVCA2: const MinMax(min: 0.0, max: 15.0),
        DataKey.eREQ: const MinMax(min: 0.0, max: 15.0),
        DataKey.usVCA1: const MinMax(min: 0.0, max: 29.0),
        DataKey.usVCA3: const MinMax(min: 0.0, max: 29.0),
        DataKey.usVCA4: const MinMax(min: 0.0, max: 29.0),
        // DataKey.ingressSetting2,
        // DataKey.ingressSetting3,
        // DataKey.ingressSetting4,
      },
    ],
    '2': [
      // 300/372
      // MFTJ
      {},
      // SDLE
      {
        DataKey.dsVVA1: const MinMax(min: 0.0, max: 20.0),
        DataKey.dsSlope1: const MinMax(min: 0.0, max: 10.0),
        DataKey.usVCA2: const MinMax(min: 0.0, max: 15.0),
        DataKey.eREQ: const MinMax(min: 0.0, max: 15.0),
        DataKey.usVCA1: const MinMax(min: 0.0, max: 29.0),
        // DataKey.ingressSetting2,
      },
      // Moto BLE
      {
        DataKey.dsVVA1: const MinMax(min: 0.0, max: 20.0),
        DataKey.dsSlope1: const MinMax(min: 0.0, max: 10.0),
        DataKey.usVCA2: const MinMax(min: 0.0, max: 15.0),
        DataKey.eREQ: const MinMax(min: 0.0, max: 15.0),
        DataKey.usVCA1: const MinMax(min: 0.0, max: 29.0),
        // DataKey.ingressSetting2,
      },
      // Moto MB
      {
        DataKey.dsVVA1: const MinMax(min: 0.0, max: 20.0),
        DataKey.dsSlope1: const MinMax(min: 0.0, max: 10.0),
        DataKey.dsVVA4: const MinMax(min: 0.0, max: 10.0),
        DataKey.usVCA2: const MinMax(min: 0.0, max: 15.0),
        DataKey.eREQ: const MinMax(min: 0.0, max: 15.0),
        DataKey.usVCA1: const MinMax(min: 0.0, max: 29.0),
        DataKey.usVCA3: const MinMax(min: 0.0, max: 29.0),
        DataKey.usVCA4: const MinMax(min: 0.0, max: 29.0),
        //  DataKey.ingressSetting2,
        //  DataKey.ingressSetting3,
        //  DataKey.ingressSetting4,
      },
      // C-Cor Node
      {
        DataKey.dsVVA1: const MinMax(min: 0.0, max: 25.0),
        DataKey.dsVVA3: const MinMax(min: 0.0, max: 25.0),
        DataKey.dsVVA4: const MinMax(min: 0.0, max: 25.0),
        DataKey.dsVVA6: const MinMax(min: 0.0, max: 25.0),
        DataKey.dsOutSlope1: const MinMax(min: 0.0, max: 8.0),
        DataKey.dsOutSlope3: const MinMax(min: 0.0, max: 8.0),
        DataKey.dsOutSlope4: const MinMax(min: 0.0, max: 8.0),
        DataKey.dsOutSlope6: const MinMax(min: 0.0, max: 8.0),
        DataKey.biasCurrent1: const MinMax(min: 320, max: 520),
        DataKey.biasCurrent3: const MinMax(min: 320, max: 520),
        DataKey.biasCurrent4: const MinMax(min: 320, max: 520),
        DataKey.biasCurrent6: const MinMax(min: 320, max: 520),
        DataKey.usVCA1: const MinMax(min: 0.0, max: 25.0),
        DataKey.usVCA3: const MinMax(min: 0.0, max: 25.0),
        DataKey.usVCA4: const MinMax(min: 0.0, max: 25.0),
        DataKey.usVCA6: const MinMax(min: 0.0, max: 25.0),
        // DataKey.ingressSetting1,
        // DataKey.ingressSetting3,
        // DataKey.ingressSetting4,
        // DataKey.ingressSetting6,
      },
      {
        // C-Cor TR
        DataKey.dsVVA1: const MinMax(min: 0.0, max: 20.0),
        DataKey.dsSlope1: const MinMax(min: 0.0, max: 10.0),
        DataKey.dsVVA4: const MinMax(min: 0.0, max: 10.0),
        DataKey.dsVVA5: const MinMax(min: 0.0, max: 10.0),
        DataKey.dsSlope3: const MinMax(min: 0.0, max: 10.0),
        DataKey.dsSlope4: const MinMax(min: 0.0, max: 10.0),
        DataKey.usVCA2: const MinMax(min: 0.0, max: 15.0),
        DataKey.eREQ: const MinMax(min: 0.0, max: 15.0),
        DataKey.usVCA1: const MinMax(min: 0.0, max: 29.0),
        DataKey.usVCA3: const MinMax(min: 0.0, max: 29.0),
        DataKey.usVCA4: const MinMax(min: 0.0, max: 29.0),
        // DataKey.ingressSetting2,
        // DataKey.ingressSetting3,
        // DataKey.ingressSetting4,
      },
      {
        // C-Cor BR
        DataKey.dsVVA1: const MinMax(min: 0.0, max: 20.0),
        DataKey.dsSlope1: const MinMax(min: 0.0, max: 10.0),
        DataKey.dsVVA4: const MinMax(min: 0.0, max: 10.0),
        DataKey.dsSlope3: const MinMax(min: 0.0, max: 10.0),
        DataKey.dsSlope4: const MinMax(min: 0.0, max: 10.0),
        DataKey.usVCA2: const MinMax(min: 0.0, max: 15.0),
        DataKey.eREQ: const MinMax(min: 0.0, max: 15.0),
        DataKey.usVCA3: const MinMax(min: 0.0, max: 29.0),
        DataKey.usVCA4: const MinMax(min: 0.0, max: 29.0),
        // DataKey.ingressSetting3,
        // DataKey.ingressSetting4,
      },
      {
        // C-Cor LE
        DataKey.dsVVA1: const MinMax(min: 0.0, max: 20.0),
        DataKey.dsSlope1: const MinMax(min: 0.0, max: 10.0),
        DataKey.usVCA2: const MinMax(min: 0.0, max: 15.0),
        DataKey.eREQ: const MinMax(min: 0.0, max: 15.0),
        DataKey.usVCA1: const MinMax(min: 0.0, max: 29.0),
        // SettingControl.returnIngressSetting2: DataKey.ingressSetting2,
      },
      {
        // SDAT
        DataKey.dsVVA1: const MinMax(min: 0.0, max: 20.0),
        DataKey.dsSlope1: const MinMax(min: 0.0, max: 10.0),
        DataKey.dsVVA4: const MinMax(min: 0.0, max: 10.0),
        DataKey.dsVVA5: const MinMax(min: 0.0, max: 10.0),
        DataKey.dsSlope3: const MinMax(min: 0.0, max: 10.0),
        DataKey.dsSlope4: const MinMax(min: 0.0, max: 10.0),
        DataKey.usVCA2: const MinMax(min: 0.0, max: 15.0),
        DataKey.eREQ: const MinMax(min: 0.0, max: 15.0),
        DataKey.usVCA1: const MinMax(min: 0.0, max: 29.0),
        DataKey.usVCA3: const MinMax(min: 0.0, max: 29.0),
        DataKey.usVCA4: const MinMax(min: 0.0, max: 29.0),
        //  DataKey.ingressSetting2,
        //  DataKey.ingressSetting3,
        //  DataKey.ingressSetting4,
      },
      {
        // SDAM
        DataKey.dsVVA1: const MinMax(min: 0.0, max: 20.0),
        DataKey.dsSlope1: const MinMax(min: 0.0, max: 10.0),
        DataKey.dsVVA4: const MinMax(min: 0.0, max: 10.0),
        DataKey.usVCA2: const MinMax(min: 0.0, max: 15.0),
        DataKey.eREQ: const MinMax(min: 0.0, max: 15.0),
        DataKey.usVCA1: const MinMax(min: 0.0, max: 29.0),
        DataKey.usVCA3: const MinMax(min: 0.0, max: 29.0),
        DataKey.usVCA4: const MinMax(min: 0.0, max: 29.0),
        // DataKey.ingressSetting2,
        // DataKey.ingressSetting3,
        // DataKey.ingressSetting4,
      },
    ],
    '3': [
      // 396/492
      // MFTJ
      {},
      // SDLE
      {
        DataKey.dsVVA1: const MinMax(min: 0.0, max: 20.0),
        DataKey.dsSlope1: const MinMax(min: 0.0, max: 10.0),
        DataKey.usVCA2: const MinMax(min: 0.0, max: 15.0),
        DataKey.eREQ: const MinMax(min: 0.0, max: 15.0),
        DataKey.usVCA1: const MinMax(min: 0.0, max: 29.0),
        // DataKey.ingressSetting2,
      },
      // Moto BLE
      {
        DataKey.dsVVA1: const MinMax(min: 0.0, max: 20.0),
        DataKey.dsSlope1: const MinMax(min: 0.0, max: 10.0),
        DataKey.usVCA2: const MinMax(min: 0.0, max: 15.0),
        DataKey.eREQ: const MinMax(min: 0.0, max: 15.0),
        DataKey.usVCA1: const MinMax(min: 0.0, max: 29.0),
        // DataKey.ingressSetting2,
      },
      // Moto MB
      {
        DataKey.dsVVA1: const MinMax(min: 0.0, max: 20.0),
        DataKey.dsSlope1: const MinMax(min: 0.0, max: 10.0),
        DataKey.dsVVA4: const MinMax(min: 0.0, max: 10.0),
        DataKey.usVCA2: const MinMax(min: 0.0, max: 15.0),
        DataKey.eREQ: const MinMax(min: 0.0, max: 15.0),
        DataKey.usVCA1: const MinMax(min: 0.0, max: 29.0),
        DataKey.usVCA3: const MinMax(min: 0.0, max: 29.0),
        DataKey.usVCA4: const MinMax(min: 0.0, max: 29.0),
        //  DataKey.ingressSetting2,
        //  DataKey.ingressSetting3,
        //  DataKey.ingressSetting4,
      },
      // C-Cor Node
      {
        DataKey.dsVVA1: const MinMax(min: 0.0, max: 25.0),
        DataKey.dsVVA3: const MinMax(min: 0.0, max: 25.0),
        DataKey.dsVVA4: const MinMax(min: 0.0, max: 25.0),
        DataKey.dsVVA6: const MinMax(min: 0.0, max: 25.0),
        DataKey.dsOutSlope1: const MinMax(min: 0.0, max: 8.0),
        DataKey.dsOutSlope3: const MinMax(min: 0.0, max: 8.0),
        DataKey.dsOutSlope4: const MinMax(min: 0.0, max: 8.0),
        DataKey.dsOutSlope6: const MinMax(min: 0.0, max: 8.0),
        DataKey.biasCurrent1: const MinMax(min: 320, max: 520),
        DataKey.biasCurrent3: const MinMax(min: 320, max: 520),
        DataKey.biasCurrent4: const MinMax(min: 320, max: 520),
        DataKey.biasCurrent6: const MinMax(min: 320, max: 520),
        DataKey.usVCA1: const MinMax(min: 0.0, max: 25.0),
        DataKey.usVCA3: const MinMax(min: 0.0, max: 25.0),
        DataKey.usVCA4: const MinMax(min: 0.0, max: 25.0),
        DataKey.usVCA6: const MinMax(min: 0.0, max: 25.0),
        // DataKey.ingressSetting1,
        // DataKey.ingressSetting3,
        // DataKey.ingressSetting4,
        // DataKey.ingressSetting6,
      },
      {
        // C-Cor TR
        DataKey.dsVVA1: const MinMax(min: 0.0, max: 20.0),
        DataKey.dsSlope1: const MinMax(min: 0.0, max: 10.0),
        DataKey.dsVVA4: const MinMax(min: 0.0, max: 10.0),
        DataKey.dsVVA5: const MinMax(min: 0.0, max: 10.0),
        DataKey.dsSlope3: const MinMax(min: 0.0, max: 10.0),
        DataKey.dsSlope4: const MinMax(min: 0.0, max: 10.0),
        DataKey.usVCA2: const MinMax(min: 0.0, max: 15.0),
        DataKey.eREQ: const MinMax(min: 0.0, max: 15.0),
        DataKey.usVCA1: const MinMax(min: 0.0, max: 29.0),
        DataKey.usVCA3: const MinMax(min: 0.0, max: 29.0),
        DataKey.usVCA4: const MinMax(min: 0.0, max: 29.0),
        // DataKey.ingressSetting2,
        // DataKey.ingressSetting3,
        // DataKey.ingressSetting4,
      },
      {
        // C-Cor BR
        DataKey.dsVVA1: const MinMax(min: 0.0, max: 20.0),
        DataKey.dsSlope1: const MinMax(min: 0.0, max: 10.0),
        DataKey.dsVVA4: const MinMax(min: 0.0, max: 10.0),
        DataKey.dsSlope3: const MinMax(min: 0.0, max: 10.0),
        DataKey.dsSlope4: const MinMax(min: 0.0, max: 10.0),
        DataKey.usVCA2: const MinMax(min: 0.0, max: 15.0),
        DataKey.eREQ: const MinMax(min: 0.0, max: 15.0),
        DataKey.usVCA3: const MinMax(min: 0.0, max: 29.0),
        DataKey.usVCA4: const MinMax(min: 0.0, max: 29.0),
        // DataKey.ingressSetting3,
        // DataKey.ingressSetting4,
      },
      {
        // C-Cor LE
        DataKey.dsVVA1: const MinMax(min: 0.0, max: 20.0),
        DataKey.dsSlope1: const MinMax(min: 0.0, max: 10.0),
        DataKey.usVCA2: const MinMax(min: 0.0, max: 15.0),
        DataKey.eREQ: const MinMax(min: 0.0, max: 15.0),
        DataKey.usVCA1: const MinMax(min: 0.0, max: 29.0),
        // SettingControl.returnIngressSetting2: DataKey.ingressSetting2,
      },
      {
        // SDAT
        DataKey.dsVVA1: const MinMax(min: 0.0, max: 20.0),
        DataKey.dsSlope1: const MinMax(min: 0.0, max: 10.0),
        DataKey.dsVVA4: const MinMax(min: 0.0, max: 10.0),
        DataKey.dsVVA5: const MinMax(min: 0.0, max: 10.0),
        DataKey.dsSlope3: const MinMax(min: 0.0, max: 10.0),
        DataKey.dsSlope4: const MinMax(min: 0.0, max: 10.0),
        DataKey.usVCA2: const MinMax(min: 0.0, max: 15.0),
        DataKey.eREQ: const MinMax(min: 0.0, max: 15.0),
        DataKey.usVCA1: const MinMax(min: 0.0, max: 29.0),
        DataKey.usVCA3: const MinMax(min: 0.0, max: 29.0),
        DataKey.usVCA4: const MinMax(min: 0.0, max: 29.0),
        //  DataKey.ingressSetting2,
        //  DataKey.ingressSetting3,
        //  DataKey.ingressSetting4,
      },
      {
        // SDAM
        DataKey.dsVVA1: const MinMax(min: 0.0, max: 20.0),
        DataKey.dsSlope1: const MinMax(min: 0.0, max: 10.0),
        DataKey.dsVVA4: const MinMax(min: 0.0, max: 10.0),
        DataKey.usVCA2: const MinMax(min: 0.0, max: 15.0),
        DataKey.eREQ: const MinMax(min: 0.0, max: 15.0),
        DataKey.usVCA1: const MinMax(min: 0.0, max: 29.0),
        DataKey.usVCA3: const MinMax(min: 0.0, max: 29.0),
        DataKey.usVCA4: const MinMax(min: 0.0, max: 29.0),
        // DataKey.ingressSetting2,
        // DataKey.ingressSetting3,
        // DataKey.ingressSetting4,
      },
    ],
    '4': [
      // 492/606
      // MFTJ
      {},
      // SDLE
      {
        DataKey.dsVVA1: const MinMax(min: 0.0, max: 20.0),
        DataKey.dsSlope1: const MinMax(min: 0.0, max: 10.0),
        DataKey.usVCA2: const MinMax(min: 0.0, max: 15.0),
        DataKey.eREQ: const MinMax(min: 0.0, max: 15.0),
        DataKey.usVCA1: const MinMax(min: 0.0, max: 29.0),
        // DataKey.ingressSetting2,
      },
      // Moto BLE
      {
        DataKey.dsVVA1: const MinMax(min: 0.0, max: 20.0),
        DataKey.dsSlope1: const MinMax(min: 0.0, max: 10.0),
        DataKey.usVCA2: const MinMax(min: 0.0, max: 15.0),
        DataKey.eREQ: const MinMax(min: 0.0, max: 15.0),
        DataKey.usVCA1: const MinMax(min: 0.0, max: 29.0),
        // DataKey.ingressSetting2,
      },
      // Moto MB
      {
        DataKey.dsVVA1: const MinMax(min: 0.0, max: 20.0),
        DataKey.dsSlope1: const MinMax(min: 0.0, max: 10.0),
        DataKey.dsVVA4: const MinMax(min: 0.0, max: 10.0),
        DataKey.usVCA2: const MinMax(min: 0.0, max: 15.0),
        DataKey.eREQ: const MinMax(min: 0.0, max: 15.0),
        DataKey.usVCA1: const MinMax(min: 0.0, max: 29.0),
        DataKey.usVCA3: const MinMax(min: 0.0, max: 29.0),
        DataKey.usVCA4: const MinMax(min: 0.0, max: 29.0),
        //  DataKey.ingressSetting2,
        //  DataKey.ingressSetting3,
        //  DataKey.ingressSetting4,
      },
      // C-Cor Node
      {
        DataKey.dsVVA1: const MinMax(min: 0.0, max: 25.0),
        DataKey.dsVVA3: const MinMax(min: 0.0, max: 25.0),
        DataKey.dsVVA4: const MinMax(min: 0.0, max: 25.0),
        DataKey.dsVVA6: const MinMax(min: 0.0, max: 25.0),
        DataKey.dsOutSlope1: const MinMax(min: 0.0, max: 8.0),
        DataKey.dsOutSlope3: const MinMax(min: 0.0, max: 8.0),
        DataKey.dsOutSlope4: const MinMax(min: 0.0, max: 8.0),
        DataKey.dsOutSlope6: const MinMax(min: 0.0, max: 8.0),
        DataKey.biasCurrent1: const MinMax(min: 320, max: 520),
        DataKey.biasCurrent3: const MinMax(min: 320, max: 520),
        DataKey.biasCurrent4: const MinMax(min: 320, max: 520),
        DataKey.biasCurrent6: const MinMax(min: 320, max: 520),
        DataKey.usVCA1: const MinMax(min: 0.0, max: 25.0),
        DataKey.usVCA3: const MinMax(min: 0.0, max: 25.0),
        DataKey.usVCA4: const MinMax(min: 0.0, max: 25.0),
        DataKey.usVCA6: const MinMax(min: 0.0, max: 25.0),
        // DataKey.ingressSetting1,
        // DataKey.ingressSetting3,
        // DataKey.ingressSetting4,
        // DataKey.ingressSetting6,
      },
      {
        // C-Cor TR
        DataKey.dsVVA1: const MinMax(min: 0.0, max: 20.0),
        DataKey.dsSlope1: const MinMax(min: 0.0, max: 10.0),
        DataKey.dsVVA4: const MinMax(min: 0.0, max: 10.0),
        DataKey.dsVVA5: const MinMax(min: 0.0, max: 10.0),
        DataKey.dsSlope3: const MinMax(min: 0.0, max: 10.0),
        DataKey.dsSlope4: const MinMax(min: 0.0, max: 10.0),
        DataKey.usVCA2: const MinMax(min: 0.0, max: 15.0),
        DataKey.eREQ: const MinMax(min: 0.0, max: 15.0),
        DataKey.usVCA1: const MinMax(min: 0.0, max: 29.0),
        DataKey.usVCA3: const MinMax(min: 0.0, max: 29.0),
        DataKey.usVCA4: const MinMax(min: 0.0, max: 29.0),
        // DataKey.ingressSetting2,
        // DataKey.ingressSetting3,
        // DataKey.ingressSetting4,
      },
      {
        // C-Cor BR
        DataKey.dsVVA1: const MinMax(min: 0.0, max: 20.0),
        DataKey.dsSlope1: const MinMax(min: 0.0, max: 10.0),
        DataKey.dsVVA4: const MinMax(min: 0.0, max: 10.0),
        DataKey.dsSlope3: const MinMax(min: 0.0, max: 10.0),
        DataKey.dsSlope4: const MinMax(min: 0.0, max: 10.0),
        DataKey.usVCA2: const MinMax(min: 0.0, max: 15.0),
        DataKey.eREQ: const MinMax(min: 0.0, max: 15.0),
        DataKey.usVCA3: const MinMax(min: 0.0, max: 29.0),
        DataKey.usVCA4: const MinMax(min: 0.0, max: 29.0),
        // DataKey.ingressSetting3,
        // DataKey.ingressSetting4,
      },
      {
        // C-Cor LE
        DataKey.dsVVA1: const MinMax(min: 0.0, max: 20.0),
        DataKey.dsSlope1: const MinMax(min: 0.0, max: 10.0),
        DataKey.usVCA2: const MinMax(min: 0.0, max: 15.0),
        DataKey.eREQ: const MinMax(min: 0.0, max: 15.0),
        DataKey.usVCA1: const MinMax(min: 0.0, max: 29.0),
        // SettingControl.returnIngressSetting2: DataKey.ingressSetting2,
      },
      {
        // SDAT
        DataKey.dsVVA1: const MinMax(min: 0.0, max: 20.0),
        DataKey.dsSlope1: const MinMax(min: 0.0, max: 10.0),
        DataKey.dsVVA4: const MinMax(min: 0.0, max: 10.0),
        DataKey.dsVVA5: const MinMax(min: 0.0, max: 10.0),
        DataKey.dsSlope3: const MinMax(min: 0.0, max: 10.0),
        DataKey.dsSlope4: const MinMax(min: 0.0, max: 10.0),
        DataKey.usVCA2: const MinMax(min: 0.0, max: 15.0),
        DataKey.eREQ: const MinMax(min: 0.0, max: 15.0),
        DataKey.usVCA1: const MinMax(min: 0.0, max: 29.0),
        DataKey.usVCA3: const MinMax(min: 0.0, max: 29.0),
        DataKey.usVCA4: const MinMax(min: 0.0, max: 29.0),
        //  DataKey.ingressSetting2,
        //  DataKey.ingressSetting3,
        //  DataKey.ingressSetting4,
      },
      {
        // SDAM
        DataKey.dsVVA1: const MinMax(min: 0.0, max: 20.0),
        DataKey.dsSlope1: const MinMax(min: 0.0, max: 10.0),
        DataKey.dsVVA4: const MinMax(min: 0.0, max: 10.0),
        DataKey.usVCA2: const MinMax(min: 0.0, max: 15.0),
        DataKey.eREQ: const MinMax(min: 0.0, max: 15.0),
        DataKey.usVCA1: const MinMax(min: 0.0, max: 29.0),
        DataKey.usVCA3: const MinMax(min: 0.0, max: 29.0),
        DataKey.usVCA4: const MinMax(min: 0.0, max: 29.0),
        // DataKey.ingressSetting2,
        // DataKey.ingressSetting3,
        // DataKey.ingressSetting4,
      },
    ],
    '5': [
      // 684/834
      // MFTJ
      {},
      // SDLE
      {
        DataKey.dsVVA1: const MinMax(min: 0.0, max: 20.0),
        DataKey.dsSlope1: const MinMax(min: 0.0, max: 10.0),
        DataKey.usVCA2: const MinMax(min: 0.0, max: 15.0),
        DataKey.eREQ: const MinMax(min: 0.0, max: 15.0),
        DataKey.usVCA1: const MinMax(min: 0.0, max: 29.0),
        // DataKey.ingressSetting2,
      },
      // Moto BLE
      {
        DataKey.dsVVA1: const MinMax(min: 0.0, max: 20.0),
        DataKey.dsSlope1: const MinMax(min: 0.0, max: 10.0),
        DataKey.usVCA2: const MinMax(min: 0.0, max: 15.0),
        DataKey.eREQ: const MinMax(min: 0.0, max: 15.0),
        DataKey.usVCA1: const MinMax(min: 0.0, max: 29.0),
        // DataKey.ingressSetting2,
      },
      // Moto MB
      {
        DataKey.dsVVA1: const MinMax(min: 0.0, max: 20.0),
        DataKey.dsSlope1: const MinMax(min: 0.0, max: 10.0),
        DataKey.dsVVA4: const MinMax(min: 0.0, max: 10.0),
        DataKey.usVCA2: const MinMax(min: 0.0, max: 15.0),
        DataKey.eREQ: const MinMax(min: 0.0, max: 15.0),
        DataKey.usVCA1: const MinMax(min: 0.0, max: 29.0),
        DataKey.usVCA3: const MinMax(min: 0.0, max: 29.0),
        DataKey.usVCA4: const MinMax(min: 0.0, max: 29.0),
        //  DataKey.ingressSetting2,
        //  DataKey.ingressSetting3,
        //  DataKey.ingressSetting4,
      },
      // C-Cor Node
      {
        DataKey.dsVVA1: const MinMax(min: 0.0, max: 25.0),
        DataKey.dsVVA3: const MinMax(min: 0.0, max: 25.0),
        DataKey.dsVVA4: const MinMax(min: 0.0, max: 25.0),
        DataKey.dsVVA6: const MinMax(min: 0.0, max: 25.0),
        DataKey.dsOutSlope1: const MinMax(min: 0.0, max: 8.0),
        DataKey.dsOutSlope3: const MinMax(min: 0.0, max: 8.0),
        DataKey.dsOutSlope4: const MinMax(min: 0.0, max: 8.0),
        DataKey.dsOutSlope6: const MinMax(min: 0.0, max: 8.0),
        DataKey.biasCurrent1: const MinMax(min: 320, max: 520),
        DataKey.biasCurrent3: const MinMax(min: 320, max: 520),
        DataKey.biasCurrent4: const MinMax(min: 320, max: 520),
        DataKey.biasCurrent6: const MinMax(min: 320, max: 520),
        DataKey.usVCA1: const MinMax(min: 0.0, max: 25.0),
        DataKey.usVCA3: const MinMax(min: 0.0, max: 25.0),
        DataKey.usVCA4: const MinMax(min: 0.0, max: 25.0),
        DataKey.usVCA6: const MinMax(min: 0.0, max: 25.0),
        // DataKey.ingressSetting1,
        // DataKey.ingressSetting3,
        // DataKey.ingressSetting4,
        // DataKey.ingressSetting6,
      },
      {
        // C-Cor TR
        DataKey.dsVVA1: const MinMax(min: 0.0, max: 20.0),
        DataKey.dsSlope1: const MinMax(min: 0.0, max: 10.0),
        DataKey.dsVVA4: const MinMax(min: 0.0, max: 10.0),
        DataKey.dsVVA5: const MinMax(min: 0.0, max: 10.0),
        DataKey.dsSlope3: const MinMax(min: 0.0, max: 10.0),
        DataKey.dsSlope4: const MinMax(min: 0.0, max: 10.0),
        DataKey.usVCA2: const MinMax(min: 0.0, max: 15.0),
        DataKey.eREQ: const MinMax(min: 0.0, max: 15.0),
        DataKey.usVCA1: const MinMax(min: 0.0, max: 29.0),
        DataKey.usVCA3: const MinMax(min: 0.0, max: 29.0),
        DataKey.usVCA4: const MinMax(min: 0.0, max: 29.0),
        // DataKey.ingressSetting2,
        // DataKey.ingressSetting3,
        // DataKey.ingressSetting4,
      },
      {
        // C-Cor BR
        DataKey.dsVVA1: const MinMax(min: 0.0, max: 20.0),
        DataKey.dsSlope1: const MinMax(min: 0.0, max: 10.0),
        DataKey.dsVVA4: const MinMax(min: 0.0, max: 10.0),
        DataKey.dsSlope3: const MinMax(min: 0.0, max: 10.0),
        DataKey.dsSlope4: const MinMax(min: 0.0, max: 10.0),
        DataKey.usVCA2: const MinMax(min: 0.0, max: 15.0),
        DataKey.eREQ: const MinMax(min: 0.0, max: 15.0),
        DataKey.usVCA3: const MinMax(min: 0.0, max: 29.0),
        DataKey.usVCA4: const MinMax(min: 0.0, max: 29.0),
        // DataKey.ingressSetting3,
        // DataKey.ingressSetting4,
      },
      {
        // C-Cor LE
        DataKey.dsVVA1: const MinMax(min: 0.0, max: 20.0),
        DataKey.dsSlope1: const MinMax(min: 0.0, max: 10.0),
        DataKey.usVCA2: const MinMax(min: 0.0, max: 15.0),
        DataKey.eREQ: const MinMax(min: 0.0, max: 15.0),
        DataKey.usVCA1: const MinMax(min: 0.0, max: 29.0),
        // SettingControl.returnIngressSetting2: DataKey.ingressSetting2,
      },
      {
        // SDAT
        DataKey.dsVVA1: const MinMax(min: 0.0, max: 20.0),
        DataKey.dsSlope1: const MinMax(min: 0.0, max: 10.0),
        DataKey.dsVVA4: const MinMax(min: 0.0, max: 10.0),
        DataKey.dsVVA5: const MinMax(min: 0.0, max: 10.0),
        DataKey.dsSlope3: const MinMax(min: 0.0, max: 10.0),
        DataKey.dsSlope4: const MinMax(min: 0.0, max: 10.0),
        DataKey.usVCA2: const MinMax(min: 0.0, max: 15.0),
        DataKey.eREQ: const MinMax(min: 0.0, max: 15.0),
        DataKey.usVCA1: const MinMax(min: 0.0, max: 29.0),
        DataKey.usVCA3: const MinMax(min: 0.0, max: 29.0),
        DataKey.usVCA4: const MinMax(min: 0.0, max: 29.0),
        //  DataKey.ingressSetting2,
        //  DataKey.ingressSetting3,
        //  DataKey.ingressSetting4,
      },
      {
        // SDAM
        DataKey.dsVVA1: const MinMax(min: 0.0, max: 20.0),
        DataKey.dsSlope1: const MinMax(min: 0.0, max: 10.0),
        DataKey.dsVVA4: const MinMax(min: 0.0, max: 10.0),
        DataKey.usVCA2: const MinMax(min: 0.0, max: 15.0),
        DataKey.eREQ: const MinMax(min: 0.0, max: 15.0),
        DataKey.usVCA1: const MinMax(min: 0.0, max: 29.0),
        DataKey.usVCA3: const MinMax(min: 0.0, max: 29.0),
        DataKey.usVCA4: const MinMax(min: 0.0, max: 29.0),
        // DataKey.ingressSetting2,
        // DataKey.ingressSetting3,
        // DataKey.ingressSetting4,
      },
    ],
    '6': [
      // 85/105
      // MFTJ
      {},
      // SDLE
      {
        DataKey.dsVVA1: const MinMax(min: 0.0, max: 20.0),
        DataKey.dsSlope1: const MinMax(min: 0.0, max: 10.0),
        DataKey.usVCA2: const MinMax(min: 0.0, max: 15.0),
        DataKey.eREQ: const MinMax(min: 0.0, max: 15.0),
        DataKey.usVCA1: const MinMax(min: 0.0, max: 29.0),
        // DataKey.ingressSetting2,
      },
      // Moto BLE
      {
        DataKey.dsVVA1: const MinMax(min: 0.0, max: 20.0),
        DataKey.dsSlope1: const MinMax(min: 0.0, max: 10.0),
        DataKey.usVCA2: const MinMax(min: 0.0, max: 15.0),
        DataKey.eREQ: const MinMax(min: 0.0, max: 15.0),
        DataKey.usVCA1: const MinMax(min: 0.0, max: 29.0),
        // DataKey.ingressSetting2,
      },
      // Moto MB
      {
        DataKey.dsVVA1: const MinMax(min: 0.0, max: 20.0),
        DataKey.dsSlope1: const MinMax(min: 0.0, max: 10.0),
        DataKey.dsVVA4: const MinMax(min: 0.0, max: 10.0),
        DataKey.usVCA2: const MinMax(min: 0.0, max: 15.0),
        DataKey.eREQ: const MinMax(min: 0.0, max: 15.0),
        DataKey.usVCA1: const MinMax(min: 0.0, max: 29.0),
        DataKey.usVCA3: const MinMax(min: 0.0, max: 29.0),
        DataKey.usVCA4: const MinMax(min: 0.0, max: 29.0),
        //  DataKey.ingressSetting2,
        //  DataKey.ingressSetting3,
        //  DataKey.ingressSetting4,
      },
      // C-Cor Node
      {
        DataKey.dsVVA1: const MinMax(min: 0.0, max: 25.0),
        DataKey.dsVVA3: const MinMax(min: 0.0, max: 25.0),
        DataKey.dsVVA4: const MinMax(min: 0.0, max: 25.0),
        DataKey.dsVVA6: const MinMax(min: 0.0, max: 25.0),
        DataKey.dsOutSlope1: const MinMax(min: 0.0, max: 8.0),
        DataKey.dsOutSlope3: const MinMax(min: 0.0, max: 8.0),
        DataKey.dsOutSlope4: const MinMax(min: 0.0, max: 8.0),
        DataKey.dsOutSlope6: const MinMax(min: 0.0, max: 8.0),
        DataKey.biasCurrent1: const MinMax(min: 320, max: 520),
        DataKey.biasCurrent3: const MinMax(min: 320, max: 520),
        DataKey.biasCurrent4: const MinMax(min: 320, max: 520),
        DataKey.biasCurrent6: const MinMax(min: 320, max: 520),
        DataKey.usVCA1: const MinMax(min: 0.0, max: 25.0),
        DataKey.usVCA3: const MinMax(min: 0.0, max: 25.0),
        DataKey.usVCA4: const MinMax(min: 0.0, max: 25.0),
        DataKey.usVCA6: const MinMax(min: 0.0, max: 25.0),
        // DataKey.ingressSetting1,
        // DataKey.ingressSetting3,
        // DataKey.ingressSetting4,
        // DataKey.ingressSetting6,
      },
      {
        // C-Cor TR
        DataKey.dsVVA1: const MinMax(min: 0.0, max: 20.0),
        DataKey.dsSlope1: const MinMax(min: 0.0, max: 10.0),
        DataKey.dsVVA4: const MinMax(min: 0.0, max: 10.0),
        DataKey.dsVVA5: const MinMax(min: 0.0, max: 10.0),
        DataKey.dsSlope3: const MinMax(min: 0.0, max: 10.0),
        DataKey.dsSlope4: const MinMax(min: 0.0, max: 10.0),
        DataKey.usVCA2: const MinMax(min: 0.0, max: 15.0),
        DataKey.eREQ: const MinMax(min: 0.0, max: 15.0),
        DataKey.usVCA1: const MinMax(min: 0.0, max: 29.0),
        DataKey.usVCA3: const MinMax(min: 0.0, max: 29.0),
        DataKey.usVCA4: const MinMax(min: 0.0, max: 29.0),
        // DataKey.ingressSetting2,
        // DataKey.ingressSetting3,
        // DataKey.ingressSetting4,
      },
      {
        // C-Cor BR
        DataKey.dsVVA1: const MinMax(min: 0.0, max: 20.0),
        DataKey.dsSlope1: const MinMax(min: 0.0, max: 10.0),
        DataKey.dsVVA4: const MinMax(min: 0.0, max: 10.0),
        DataKey.dsSlope3: const MinMax(min: 0.0, max: 10.0),
        DataKey.dsSlope4: const MinMax(min: 0.0, max: 10.0),
        DataKey.usVCA2: const MinMax(min: 0.0, max: 15.0),
        DataKey.eREQ: const MinMax(min: 0.0, max: 15.0),
        DataKey.usVCA3: const MinMax(min: 0.0, max: 29.0),
        DataKey.usVCA4: const MinMax(min: 0.0, max: 29.0),
        // DataKey.ingressSetting3,
        // DataKey.ingressSetting4,
      },
      {
        // C-Cor LE
        DataKey.dsVVA1: const MinMax(min: 0.0, max: 20.0),
        DataKey.dsSlope1: const MinMax(min: 0.0, max: 10.0),
        DataKey.usVCA2: const MinMax(min: 0.0, max: 15.0),
        DataKey.eREQ: const MinMax(min: 0.0, max: 15.0),
        DataKey.usVCA1: const MinMax(min: 0.0, max: 29.0),
        // SettingControl.returnIngressSetting2: DataKey.ingressSetting2,
      },
      {
        // SDAT
        DataKey.dsVVA1: const MinMax(min: 0.0, max: 20.0),
        DataKey.dsSlope1: const MinMax(min: 0.0, max: 10.0),
        DataKey.dsVVA4: const MinMax(min: 0.0, max: 10.0),
        DataKey.dsVVA5: const MinMax(min: 0.0, max: 10.0),
        DataKey.dsSlope3: const MinMax(min: 0.0, max: 10.0),
        DataKey.dsSlope4: const MinMax(min: 0.0, max: 10.0),
        DataKey.usVCA2: const MinMax(min: 0.0, max: 15.0),
        DataKey.eREQ: const MinMax(min: 0.0, max: 15.0),
        DataKey.usVCA1: const MinMax(min: 0.0, max: 29.0),
        DataKey.usVCA3: const MinMax(min: 0.0, max: 29.0),
        DataKey.usVCA4: const MinMax(min: 0.0, max: 29.0),
        //  DataKey.ingressSetting2,
        //  DataKey.ingressSetting3,
        //  DataKey.ingressSetting4,
      },
      {
        // SDAM
        DataKey.dsVVA1: const MinMax(min: 0.0, max: 20.0),
        DataKey.dsSlope1: const MinMax(min: 0.0, max: 10.0),
        DataKey.dsVVA4: const MinMax(min: 0.0, max: 10.0),
        DataKey.usVCA2: const MinMax(min: 0.0, max: 15.0),
        DataKey.eREQ: const MinMax(min: 0.0, max: 15.0),
        DataKey.usVCA1: const MinMax(min: 0.0, max: 29.0),
        DataKey.usVCA3: const MinMax(min: 0.0, max: 29.0),
        DataKey.usVCA4: const MinMax(min: 0.0, max: 29.0),
        // DataKey.ingressSetting2,
        // DataKey.ingressSetting3,
        // DataKey.ingressSetting4,
      },
    ],
  };
}

class MinMax {
  const MinMax({
    required this.min,
    required this.max,
  });

  final double min;
  final double max;
}
