enum DataKey {
  partName,
  partNo,
  partId,
  serialNumber,
  firmwareVersion,
  mfgDate,
  location,
  coordinates,
  workingMode,
  currentPilot,
  currentPilotMode,
  logInterval,
  nowDateTime,
  hasDualPilot,
  alarmRSeverity,
  alarmTSeverity,
  alarmPSeverity,
  unitStatusAlarmSeverity,
  rfInputPilotLowFrequencyAlarmSeverity,
  rfInputPilotHighFrequencyAlarmSeverity,
  rfOutputPilotLowFrequencyAlarmSeverity,
  rfOutputPilotHighFrequencyAlarmSeverity,
  rfOutputPower1AlarmSeverity,
  rfOutputPower3AlarmSeverity,
  rfOutputPower4AlarmSeverity,
  rfOutputPower6AlarmSeverity,
  temperatureAlarmSeverity,
  voltageAlarmSeverity,
  splitOptionAlarmSeverity,
  voltageRippleAlarmSeverity,
  outputPowerAlarmSeverity,
  currentAttenuation,
  minAttenuation,
  centerAttenuation,
  maxAttenuation,
  historicalMinAttenuation,
  historicalMaxAttenuation,
  currentTemperatureF,
  minTemperatureF,
  maxTemperatureF,
  historicalMinTemperatureF,
  historicalMaxTemperatureF,
  currentTemperatureC,
  minTemperatureC,
  maxTemperatureC,
  historicalMinTemperatureC,
  historicalMaxTemperatureC,
  currentVoltage,
  minVoltage,
  maxVoltage,
  historicalMinVoltage,
  historicalMaxVoltage,
  historicalMinVoltageRipple,
  historicalMaxVoltageRipple,
  currentVoltageRipple,
  minVoltageRipple,
  maxVoltageRipple,
  tgcCableLength,
  splitOption,
  currentRFInputPower1p8G,
  currentRFInputPower,
  currentRFOutputPower,
  currentRFOutputPower1,
  currentRFOutputPower3,
  currentRFOutputPower4,
  currentRFOutputPower6,
  historicalMinRFOutputPower,
  historicalMaxRFOutputPower,
  historicalMinRFOutputPower1,
  historicalMaxRFOutputPower1,
  historicalMinRFOutputPower3,
  historicalMaxRFOutputPower3,
  historicalMinRFOutputPower4,
  historicalMaxRFOutputPower4,
  historicalMinRFOutputPower6,
  historicalMaxRFOutputPower6,
  minRFOutputPower,
  maxRFOutputPower,
  maxRFOutputPower1,
  minRFOutputPower1,
  maxRFOutputPower3,
  minRFOutputPower3,
  maxRFOutputPower4,
  minRFOutputPower4,
  maxRFOutputPower6,
  minRFOutputPower6,
  currentWorkingMode,
  currentDetectedSplitOption,
  rfOutputOperatingSlope,
  manualModePilot1RFOutputPower,
  manualModePilot2RFOutputPower,
  rfOutputLowChannelPower,
  rfOutputHighChannelPower,
  pilot1RFChannelFrequency,
  pilot2RFChannelFrequency,
  agcMode,
  alcMode,
  pilotFrequencyMode,
  pilotFrequency1,
  pilotFrequency2,
  firstChannelLoadingFrequency,
  lastChannelLoadingFrequency,
  firstChannelLoadingLevel,
  lastChannelLoadingLevel,
  ingressSetting1,
  ingressSetting2,
  ingressSetting3,
  ingressSetting4,
  ingressSetting6,
  // pilotFrequency1AlarmState,
  // pilotFrequency2AlarmState,
  rfOutputPilotLowFrequencyAlarmState,
  rfOutputPilotHighFrequencyAlarmState,
  temperatureAlarmState,
  voltageAlarmState,
  splitOptionAlarmState,
  voltageRippleAlarmState,
  rfOutputPowerAlarmState,
  rfOutputPower1AlarmState,
  rfOutputPower3AlarmState,
  rfOutputPower4AlarmState,
  rfOutputPower6AlarmState,
  usVCA1,
  usVCA2,
  usVCA3,
  usVCA4,
  usVCA6,
  eREQ,
  dsVVA1,
  dsVVA2,
  dsVVA3,
  dsVVA4,
  dsVVA5,
  dsVVA6,
  dsSlope1,
  dsSlope2,
  dsSlope3,
  dsSlope4,
  dsInSlope1,
  dsInSlope3,
  dsInSlope4,
  dsInSlope6,
  dsOutSlope1,
  dsOutSlope3,
  dsOutSlope4,
  dsOutSlope6,
  // forwardVVA1,
  // forwardInSlope1,
  // forwardOutSlope1,
  // returnVCA1,
  // forwardVVA3,
  // forwardInSlope3,
  // forwardOutSlope3,
  // returnVCA3,
  // forwardVVA4,
  // forwardInSlope4,
  // forwardOutSlope4,
  // returnVCA4,
  // forwardVVA6,
  // forwardInSlope6,
  // forwardOutSlope6,
  // returnVCA6,
  currentDSVVA1,
  currentDSSlope1,
  currentDSInSlope1,
  currentDSOutSlope1,
  currentUSVCA1,
  currentDSVVA3,
  currentDSInSlope3,
  currentDSOutSlope3,
  currentUSVCA3,
  currentDSVVA4,
  currentDSInSlope4,
  currentDSOutSlope4,
  currentUSVCA4,
  currentDSVVA6,
  currentDSInSlope6,
  currentDSOutSlope6,
  currentUSVCA6,
}
