import 'package:aci_plus_app/core/data_key.dart';

enum SettingConfiruration {
  location,
  coordinates,
  splitOptions,
  pilotFrequencySelect,
  startFrequency,
  stopFrequency,
  startLevel, // 為了匯出 configuration 資料而加的
  stopLevel, // 為了匯出 configuration 資料而加的
  pilot1,
  pilot2,
  agcMode,
  alcMode,
  logInterval,
  rfOutputLogInterval,
  cableLength,
}

enum SettingThreshold {
  workingMode,
  splitOptions,
  temperature,
  inputVoltage24V,
  inputVoltage8V,
  inputVoltage5p2V,
  inputVoltage3p3V,
  inputVoltageRipple24V,
  inputPower1p8G,
  outputPower,
  outputPower1,
  outputPower2,
  outputPower3,
  outputPower4,
  outputPower5,
  outputPower6,
  pilot1Status,
  pilot2Status,
  startFrequencyOutputLevel,
  stopFrequencyOutputLevel,
  operatingSlope,
  outputAttenuation1,
  outputAttenuation2,
  outputAttenuation3,
  outputAttenuation4,
  outputAttenuation5,
  outputAttenuation6,
  outputEqualizer1,
  outputEqualizer2,
  outputEqualizer3,
  outputEqualizer4,
  outputEqualizer5,
  outputEqualizer6,
}

enum SettingControl {
  forwardInputAttenuation1,
  forwardInputAttenuation2,
  forwardInputAttenuation3,
  forwardInputAttenuation4,
  forwardInputAttenuation5,
  forwardInputAttenuation6,
  forwardInputEqualizer1,
  forwardInputEqualizer2,
  forwardInputEqualizer3,
  forwardInputEqualizer4,
  forwardInputEqualizer5,
  forwardInputEqualizer6,
  forwardOutputEqualizer2And3,
  forwardOutputEqualizer3And4,
  forwardOutputEqualizer5And6,
  forwardOutputAttenuation2And3,
  forwardOutputAttenuation3And4,
  forwardOutputAttenuation5And6,
  returnOutputAttenuation1,
  returnOutputEqualizer1,
  returnInputAttenuation1,
  returnInputAttenuation2,
  returnInputAttenuation3,
  returnInputAttenuation4,
  returnInputAttenuation5,
  returnInputAttenuation6,
  returnInputAttenuation2And3,
  returnInputAttenuation5And6,
  returnIngressSetting1,
  returnIngressSetting2,
  returnIngressSetting3,
  returnIngressSetting4,
  returnIngressSetting5,
  returnIngressSetting6,
  returnIngressSetting2And3,
  returnIngressSetting5And6,
}

// 0: MFTJ (預留, app不適用)
// 1: SDLE
// 2: MOTO BLE
// 3: MOTO MB
// 4: C-Cor Node
// 5: C-Cor TR
// 6: C-Cor BR
// 7: C-Cor LE

const Map<String, String> partIdMap = {
  'd': 'DSIM',
  '0': 'MFTJ',
  '1': 'SDLE',
  '2': 'AMT BLE',
  '3': 'AMT MB',
  '4': 'AFM Node',
  '5': 'AFM TR',
  '6': 'AFM BR',
  '7': 'AFM LE',
};

const Map<String, String> settingGraphFilePath = {
  '1': '',
  '2': '',
  '3': '', // assets/circuits/MB_1.8G_20231117.svg
  '4': '',
  '5': '',
  '6': '',
  '7': '',
};

const Map<String, String> namePlateFilePath = {
  '1': '',
  '2': 'assets/nameplates/BLE.png',
  '3': 'assets/nameplates/MB.png',
  '4': '',
  '5': 'assets/nameplates/TR.png',
  '6': 'assets/nameplates/BR.png',
  '7': 'assets/nameplates/LE.png',
};

class SettingItemTable {
  static Map<String, Map<Enum, bool>> itemsMap = {
    '1': {
      // SDLE
      SettingConfiruration.location: true,
      SettingConfiruration.coordinates: true,
      SettingConfiruration.splitOptions: true,
      SettingConfiruration.pilotFrequencySelect: true,
      SettingConfiruration.startFrequency: true,
      SettingConfiruration.stopFrequency: true,
      SettingConfiruration.pilot1: true,
      SettingConfiruration.pilot2: true,
      SettingConfiruration.agcMode: true,
      SettingConfiruration.alcMode: true,
      SettingConfiruration.logInterval: true,
      SettingConfiruration.rfOutputLogInterval: true,
      SettingConfiruration.cableLength: true,
      SettingThreshold.workingMode: true,
      SettingThreshold.splitOptions: true,
      SettingThreshold.temperature: true,
      SettingThreshold.inputVoltage24V: true,
      SettingThreshold.inputVoltage8V: false,
      SettingThreshold.inputVoltage5p2V: false,
      SettingThreshold.inputVoltage3p3V: false,
      SettingThreshold.inputVoltageRipple24V: true,
      SettingThreshold.inputPower1p8G: false,
      SettingThreshold.outputPower: true,
      SettingThreshold.outputPower1: false,
      SettingThreshold.outputPower2: false,
      SettingThreshold.outputPower3: false,
      SettingThreshold.outputPower4: false,
      SettingThreshold.outputPower5: false,
      SettingThreshold.outputPower6: false,
      SettingThreshold.pilot1Status: true,
      SettingThreshold.pilot2Status: true,
      SettingThreshold.startFrequencyOutputLevel: true,
      SettingThreshold.stopFrequencyOutputLevel: true,
      SettingThreshold.operatingSlope: false,
      SettingThreshold.outputAttenuation1: false,
      SettingThreshold.outputAttenuation2: false,
      SettingThreshold.outputAttenuation3: false,
      SettingThreshold.outputAttenuation4: false,
      SettingThreshold.outputAttenuation5: false,
      SettingThreshold.outputAttenuation6: false,
      SettingThreshold.outputEqualizer1: false,
      SettingThreshold.outputEqualizer2: false,
      SettingThreshold.outputEqualizer3: false,
      SettingThreshold.outputEqualizer4: false,
      SettingThreshold.outputEqualizer5: false,
      SettingThreshold.outputEqualizer6: false,
      SettingControl.forwardInputAttenuation1: true,
      SettingControl.forwardInputAttenuation2: false,
      SettingControl.forwardInputAttenuation3: false,
      SettingControl.forwardInputAttenuation4: false,
      SettingControl.forwardInputAttenuation5: false,
      SettingControl.forwardInputAttenuation6: false,
      SettingControl.forwardInputEqualizer1: true,
      SettingControl.forwardInputEqualizer2: false,
      SettingControl.forwardInputEqualizer3: false,
      SettingControl.forwardInputEqualizer4: false,
      SettingControl.forwardInputEqualizer5: false,
      SettingControl.forwardInputEqualizer6: false,
      SettingControl.forwardOutputAttenuation2And3: false,
      SettingControl.forwardOutputAttenuation3And4: false,
      SettingControl.forwardOutputAttenuation5And6: false,
      SettingControl.forwardOutputEqualizer2And3: false,
      SettingControl.forwardOutputEqualizer3And4: false,
      SettingControl.forwardOutputEqualizer5And6: false,
      SettingControl.returnOutputAttenuation1: true,
      SettingControl.returnOutputEqualizer1: true,
      SettingControl.returnInputAttenuation1: false,
      SettingControl.returnInputAttenuation2: true,
      SettingControl.returnInputAttenuation3: false,
      SettingControl.returnInputAttenuation4: false,
      SettingControl.returnInputAttenuation5: false,
      SettingControl.returnInputAttenuation6: false,
      SettingControl.returnInputAttenuation2And3: false,
      SettingControl.returnInputAttenuation5And6: false,
      SettingControl.returnIngressSetting1: false,
      SettingControl.returnIngressSetting2: true,
      SettingControl.returnIngressSetting3: false,
      SettingControl.returnIngressSetting4: false,
      SettingControl.returnIngressSetting5: false,
      SettingControl.returnIngressSetting6: false,
      SettingControl.returnIngressSetting2And3: false,
      SettingControl.returnIngressSetting5And6: false,
    },
    '2': {
      // Moto BLE
      SettingConfiruration.location: true,
      SettingConfiruration.coordinates: true,
      SettingConfiruration.splitOptions: true,
      SettingConfiruration.pilotFrequencySelect: true,
      SettingConfiruration.startFrequency: true,
      SettingConfiruration.stopFrequency: true,
      SettingConfiruration.pilot1: true,
      SettingConfiruration.pilot2: true,
      SettingConfiruration.agcMode: true,
      SettingConfiruration.alcMode: true,
      SettingConfiruration.logInterval: true,
      SettingConfiruration.rfOutputLogInterval: true,
      SettingConfiruration.cableLength: true,
      SettingThreshold.workingMode: true,
      SettingThreshold.splitOptions: true,
      SettingThreshold.temperature: true,
      SettingThreshold.inputVoltage24V: true,
      SettingThreshold.inputVoltage8V: false,
      SettingThreshold.inputVoltage5p2V: false,
      SettingThreshold.inputVoltage3p3V: false,
      SettingThreshold.inputVoltageRipple24V: true,
      SettingThreshold.inputPower1p8G: false,
      SettingThreshold.outputPower: true,
      SettingThreshold.outputPower1: false,
      SettingThreshold.outputPower2: false,
      SettingThreshold.outputPower3: false,
      SettingThreshold.outputPower4: false,
      SettingThreshold.outputPower5: false,
      SettingThreshold.outputPower6: false,
      SettingThreshold.pilot1Status: true,
      SettingThreshold.pilot2Status: true,
      SettingThreshold.startFrequencyOutputLevel: true,
      SettingThreshold.stopFrequencyOutputLevel: true,
      SettingThreshold.operatingSlope: false,
      SettingThreshold.outputAttenuation1: false,
      SettingThreshold.outputAttenuation2: false,
      SettingThreshold.outputAttenuation3: false,
      SettingThreshold.outputAttenuation4: false,
      SettingThreshold.outputAttenuation5: false,
      SettingThreshold.outputAttenuation6: false,
      SettingThreshold.outputEqualizer1: false,
      SettingThreshold.outputEqualizer2: false,
      SettingThreshold.outputEqualizer3: false,
      SettingThreshold.outputEqualizer4: false,
      SettingThreshold.outputEqualizer5: false,
      SettingThreshold.outputEqualizer6: false,
      SettingControl.forwardInputAttenuation1: true,
      SettingControl.forwardInputAttenuation2: false,
      SettingControl.forwardInputAttenuation3: false,
      SettingControl.forwardInputAttenuation4: false,
      SettingControl.forwardInputAttenuation5: false,
      SettingControl.forwardInputAttenuation6: false,
      SettingControl.forwardInputEqualizer1: true,
      SettingControl.forwardInputEqualizer2: false,
      SettingControl.forwardInputEqualizer3: false,
      SettingControl.forwardInputEqualizer4: false,
      SettingControl.forwardInputEqualizer5: false,
      SettingControl.forwardInputEqualizer6: false,
      SettingControl.forwardOutputAttenuation2And3: false,
      SettingControl.forwardOutputAttenuation3And4: false,
      SettingControl.forwardOutputAttenuation5And6: false,
      SettingControl.forwardOutputEqualizer2And3: false,
      SettingControl.forwardOutputEqualizer3And4: false,
      SettingControl.forwardOutputEqualizer5And6: false,
      SettingControl.returnOutputAttenuation1: true,
      SettingControl.returnOutputEqualizer1: true,
      SettingControl.returnInputAttenuation1: false,
      SettingControl.returnInputAttenuation2: true,
      SettingControl.returnInputAttenuation3: false,
      SettingControl.returnInputAttenuation4: false,
      SettingControl.returnInputAttenuation5: false,
      SettingControl.returnInputAttenuation6: false,
      SettingControl.returnInputAttenuation2And3: false,
      SettingControl.returnInputAttenuation5And6: false,
      SettingControl.returnIngressSetting1: false,
      SettingControl.returnIngressSetting2: true,
      SettingControl.returnIngressSetting3: false,
      SettingControl.returnIngressSetting4: false,
      SettingControl.returnIngressSetting5: false,
      SettingControl.returnIngressSetting6: false,
      SettingControl.returnIngressSetting2And3: false,
      SettingControl.returnIngressSetting5And6: false,
    },
    '3': {
      // Moto MB
      SettingConfiruration.location: true,
      SettingConfiruration.coordinates: true,
      SettingConfiruration.splitOptions: true,
      SettingConfiruration.pilotFrequencySelect: true,
      SettingConfiruration.startFrequency: true,
      SettingConfiruration.stopFrequency: true,
      SettingConfiruration.pilot1: true,
      SettingConfiruration.pilot2: true,
      SettingConfiruration.agcMode: true,
      SettingConfiruration.alcMode: true,
      SettingConfiruration.logInterval: true,
      SettingConfiruration.rfOutputLogInterval: true,
      SettingConfiruration.cableLength: true,
      SettingThreshold.workingMode: true,
      SettingThreshold.splitOptions: true,
      SettingThreshold.temperature: true,
      SettingThreshold.inputVoltage24V: true,
      SettingThreshold.inputVoltage8V: false,
      SettingThreshold.inputVoltage5p2V: false,
      SettingThreshold.inputVoltage3p3V: false,
      SettingThreshold.inputVoltageRipple24V: true,
      SettingThreshold.inputPower1p8G: false,
      SettingThreshold.outputPower: true,
      SettingThreshold.outputPower1: false,
      SettingThreshold.outputPower2: false,
      SettingThreshold.outputPower3: false,
      SettingThreshold.outputPower4: false,
      SettingThreshold.outputPower5: false,
      SettingThreshold.outputPower6: false,
      SettingThreshold.pilot1Status: true,
      SettingThreshold.pilot2Status: true,
      SettingThreshold.startFrequencyOutputLevel: true,
      SettingThreshold.stopFrequencyOutputLevel: true,
      SettingThreshold.operatingSlope: false,
      SettingThreshold.outputAttenuation1: false,
      SettingThreshold.outputAttenuation2: false,
      SettingThreshold.outputAttenuation3: false,
      SettingThreshold.outputAttenuation4: false,
      SettingThreshold.outputAttenuation5: false,
      SettingThreshold.outputAttenuation6: false,
      SettingThreshold.outputEqualizer1: false,
      SettingThreshold.outputEqualizer2: false,
      SettingThreshold.outputEqualizer3: false,
      SettingThreshold.outputEqualizer4: false,
      SettingThreshold.outputEqualizer5: false,
      SettingThreshold.outputEqualizer6: false,
      SettingControl.forwardInputAttenuation1: true,
      SettingControl.forwardInputAttenuation2: false,
      SettingControl.forwardInputAttenuation3: false,
      SettingControl.forwardInputAttenuation4: false,
      SettingControl.forwardInputAttenuation5: false,
      SettingControl.forwardInputAttenuation6: false,
      SettingControl.forwardInputEqualizer1: true,
      SettingControl.forwardInputEqualizer2: false,
      SettingControl.forwardInputEqualizer3: false,
      SettingControl.forwardInputEqualizer4: false,
      SettingControl.forwardInputEqualizer5: false,
      SettingControl.forwardInputEqualizer6: false,
      SettingControl.forwardOutputAttenuation2And3: false,
      SettingControl.forwardOutputAttenuation3And4: true,
      SettingControl.forwardOutputAttenuation5And6: false,
      SettingControl.forwardOutputEqualizer2And3: false,
      SettingControl.forwardOutputEqualizer3And4: false,
      SettingControl.forwardOutputEqualizer5And6: false,
      SettingControl.returnOutputAttenuation1: true,
      SettingControl.returnOutputEqualizer1: true,
      SettingControl.returnInputAttenuation1: false,
      SettingControl.returnInputAttenuation2: true,
      SettingControl.returnInputAttenuation3: true,
      SettingControl.returnInputAttenuation4: true,
      SettingControl.returnInputAttenuation5: false,
      SettingControl.returnInputAttenuation6: false,
      SettingControl.returnInputAttenuation2And3: false,
      SettingControl.returnInputAttenuation5And6: false,
      SettingControl.returnIngressSetting1: false,
      SettingControl.returnIngressSetting2: true,
      SettingControl.returnIngressSetting3: true,
      SettingControl.returnIngressSetting4: true,
      SettingControl.returnIngressSetting5: false,
      SettingControl.returnIngressSetting6: false,
      SettingControl.returnIngressSetting2And3: false,
      SettingControl.returnIngressSetting5And6: false,
    },
    '4': {
      // C-Cor Node
      SettingConfiruration.location: true,
      SettingConfiruration.coordinates: true,
      SettingConfiruration.splitOptions: true,
      SettingConfiruration.pilotFrequencySelect: false,
      SettingConfiruration.startFrequency: false,
      SettingConfiruration.stopFrequency: false,
      SettingConfiruration.pilot1: false,
      SettingConfiruration.pilot2: false,
      SettingConfiruration.agcMode: false,
      SettingConfiruration.alcMode: false,
      SettingConfiruration.logInterval: true,
      SettingConfiruration.rfOutputLogInterval: false,
      SettingConfiruration.cableLength: false,
      SettingThreshold.workingMode: false,
      SettingThreshold.splitOptions: true,
      SettingThreshold.temperature: true,
      SettingThreshold.inputVoltage24V: true,
      SettingThreshold.inputVoltage8V: false,
      SettingThreshold.inputVoltage5p2V: false,
      SettingThreshold.inputVoltage3p3V: false,
      SettingThreshold.inputVoltageRipple24V: false,
      SettingThreshold.inputPower1p8G: false,
      SettingThreshold.outputPower: true,
      SettingThreshold.outputPower1: true,
      SettingThreshold.outputPower2: false,
      SettingThreshold.outputPower3: true,
      SettingThreshold.outputPower4: true,
      SettingThreshold.outputPower5: false,
      SettingThreshold.outputPower6: true,
      SettingThreshold.pilot1Status: false,
      SettingThreshold.pilot2Status: false,
      SettingThreshold.startFrequencyOutputLevel: false,
      SettingThreshold.stopFrequencyOutputLevel: false,
      SettingThreshold.operatingSlope: false,
      SettingThreshold.outputAttenuation1: true,
      SettingThreshold.outputAttenuation2: false,
      SettingThreshold.outputAttenuation3: true,
      SettingThreshold.outputAttenuation4: true,
      SettingThreshold.outputAttenuation5: false,
      SettingThreshold.outputAttenuation6: true,
      SettingThreshold.outputEqualizer1: true,
      SettingThreshold.outputEqualizer2: false,
      SettingThreshold.outputEqualizer3: true,
      SettingThreshold.outputEqualizer4: true,
      SettingThreshold.outputEqualizer5: false,
      SettingThreshold.outputEqualizer6: true,
      SettingControl.forwardInputAttenuation1: true,
      SettingControl.forwardInputAttenuation2: false,
      SettingControl.forwardInputAttenuation3: true,
      SettingControl.forwardInputAttenuation4: true,
      SettingControl.forwardInputAttenuation5: false,
      SettingControl.forwardInputAttenuation6: true,
      SettingControl.forwardInputEqualizer1: true,
      SettingControl.forwardInputEqualizer2: false,
      SettingControl.forwardInputEqualizer3: true,
      SettingControl.forwardInputEqualizer4: true,
      SettingControl.forwardInputEqualizer5: false,
      SettingControl.forwardInputEqualizer6: true,
      SettingControl.forwardOutputAttenuation2And3: false,
      SettingControl.forwardOutputAttenuation3And4: false,
      SettingControl.forwardOutputAttenuation5And6: false,
      SettingControl.forwardOutputEqualizer2And3: false,
      SettingControl.forwardOutputEqualizer3And4: false,
      SettingControl.forwardOutputEqualizer5And6: false,
      SettingControl.returnOutputAttenuation1: false,
      SettingControl.returnOutputEqualizer1: false,
      SettingControl.returnInputAttenuation1: true,
      SettingControl.returnInputAttenuation2: false,
      SettingControl.returnInputAttenuation3: true,
      SettingControl.returnInputAttenuation4: true,
      SettingControl.returnInputAttenuation5: false,
      SettingControl.returnInputAttenuation6: true,
      SettingControl.returnInputAttenuation2And3: false,
      SettingControl.returnInputAttenuation5And6: false,
      SettingControl.returnIngressSetting1: true,
      SettingControl.returnIngressSetting2: false,
      SettingControl.returnIngressSetting3: true,
      SettingControl.returnIngressSetting4: true,
      SettingControl.returnIngressSetting5: false,
      SettingControl.returnIngressSetting6: true,
      SettingControl.returnIngressSetting2And3: false,
      SettingControl.returnIngressSetting5And6: false,
    },
    '5': {
      // C-Cor TR
      SettingConfiruration.location: true,
      SettingConfiruration.coordinates: true,
      SettingConfiruration.splitOptions: true,
      SettingConfiruration.pilotFrequencySelect: true,
      SettingConfiruration.startFrequency: true,
      SettingConfiruration.stopFrequency: true,
      SettingConfiruration.pilot1: true,
      SettingConfiruration.pilot2: true,
      SettingConfiruration.agcMode: true,
      SettingConfiruration.alcMode: true,
      SettingConfiruration.logInterval: true,
      SettingConfiruration.rfOutputLogInterval: true,
      SettingConfiruration.cableLength: true,
      SettingThreshold.workingMode: true,
      SettingThreshold.splitOptions: true,
      SettingThreshold.temperature: true,
      SettingThreshold.inputVoltage24V: true,
      SettingThreshold.inputVoltage8V: false,
      SettingThreshold.inputVoltage5p2V: false,
      SettingThreshold.inputVoltage3p3V: false,
      SettingThreshold.inputVoltageRipple24V: true,
      SettingThreshold.inputPower1p8G: false,
      SettingThreshold.outputPower: true,
      SettingThreshold.outputPower1: false,
      SettingThreshold.outputPower2: false,
      SettingThreshold.outputPower3: false,
      SettingThreshold.outputPower4: false,
      SettingThreshold.outputPower5: false,
      SettingThreshold.outputPower6: false,
      SettingThreshold.pilot1Status: true,
      SettingThreshold.pilot2Status: true,
      SettingThreshold.startFrequencyOutputLevel: true,
      SettingThreshold.stopFrequencyOutputLevel: true,
      SettingThreshold.operatingSlope: false,
      SettingThreshold.outputAttenuation1: false,
      SettingThreshold.outputAttenuation2: false,
      SettingThreshold.outputAttenuation3: false,
      SettingThreshold.outputAttenuation4: false,
      SettingThreshold.outputAttenuation5: false,
      SettingThreshold.outputAttenuation6: false,
      SettingThreshold.outputEqualizer1: false,
      SettingThreshold.outputEqualizer2: false,
      SettingThreshold.outputEqualizer3: false,
      SettingThreshold.outputEqualizer4: false,
      SettingThreshold.outputEqualizer5: false,
      SettingThreshold.outputEqualizer6: false,
      SettingControl.forwardInputAttenuation1: true,
      SettingControl.forwardInputAttenuation2: false,
      SettingControl.forwardInputAttenuation3: false,
      SettingControl.forwardInputAttenuation4: false,
      SettingControl.forwardInputAttenuation5: false,
      SettingControl.forwardInputAttenuation6: false,
      SettingControl.forwardInputEqualizer1: true,
      SettingControl.forwardInputEqualizer2: false,
      SettingControl.forwardInputEqualizer3: false,
      SettingControl.forwardInputEqualizer4: false,
      SettingControl.forwardInputEqualizer5: false,
      SettingControl.forwardInputEqualizer6: false,
      SettingControl.forwardOutputAttenuation2And3: true,
      SettingControl.forwardOutputAttenuation3And4: false,
      SettingControl.forwardOutputAttenuation5And6: true,
      SettingControl.forwardOutputEqualizer2And3: true,
      SettingControl.forwardOutputEqualizer3And4: false,
      SettingControl.forwardOutputEqualizer5And6: true,
      SettingControl.returnOutputAttenuation1: true,
      SettingControl.returnOutputEqualizer1: true,
      SettingControl.returnInputAttenuation1: false,
      SettingControl.returnInputAttenuation2: false,
      SettingControl.returnInputAttenuation3: false,
      SettingControl.returnInputAttenuation4: true,
      SettingControl.returnInputAttenuation5: false,
      SettingControl.returnInputAttenuation6: false,
      SettingControl.returnInputAttenuation2And3: true,
      SettingControl.returnInputAttenuation5And6: true,
      SettingControl.returnIngressSetting1: false,
      SettingControl.returnIngressSetting2: false,
      SettingControl.returnIngressSetting3: false,
      SettingControl.returnIngressSetting4: true,
      SettingControl.returnIngressSetting5: false,
      SettingControl.returnIngressSetting6: false,
      SettingControl.returnIngressSetting2And3: true,
      SettingControl.returnIngressSetting5And6: true,
    },
    '6': {
      // C-Cor BR
      SettingConfiruration.location: true,
      SettingConfiruration.coordinates: true,
      SettingConfiruration.splitOptions: true,
      SettingConfiruration.pilotFrequencySelect: true,
      SettingConfiruration.startFrequency: true,
      SettingConfiruration.stopFrequency: true,
      SettingConfiruration.pilot1: true,
      SettingConfiruration.pilot2: true,
      SettingConfiruration.agcMode: true,
      SettingConfiruration.alcMode: true,
      SettingConfiruration.logInterval: true,
      SettingConfiruration.rfOutputLogInterval: true,
      SettingConfiruration.cableLength: true,
      SettingThreshold.workingMode: true,
      SettingThreshold.splitOptions: true,
      SettingThreshold.temperature: true,
      SettingThreshold.inputVoltage24V: true,
      SettingThreshold.inputVoltage8V: false,
      SettingThreshold.inputVoltage5p2V: false,
      SettingThreshold.inputVoltage3p3V: false,
      SettingThreshold.inputVoltageRipple24V: true,
      SettingThreshold.inputPower1p8G: true,
      SettingThreshold.outputPower: true,
      SettingThreshold.outputPower1: false,
      SettingThreshold.outputPower2: false,
      SettingThreshold.outputPower3: false,
      SettingThreshold.outputPower4: false,
      SettingThreshold.outputPower5: false,
      SettingThreshold.outputPower6: false,
      SettingThreshold.pilot1Status: true,
      SettingThreshold.pilot2Status: true,
      SettingThreshold.startFrequencyOutputLevel: true,
      SettingThreshold.stopFrequencyOutputLevel: true,
      SettingThreshold.operatingSlope: false,
      SettingThreshold.outputAttenuation1: false,
      SettingThreshold.outputAttenuation2: false,
      SettingThreshold.outputAttenuation3: false,
      SettingThreshold.outputAttenuation4: false,
      SettingThreshold.outputAttenuation5: false,
      SettingThreshold.outputAttenuation6: false,
      SettingThreshold.outputEqualizer1: false,
      SettingThreshold.outputEqualizer2: false,
      SettingThreshold.outputEqualizer3: false,
      SettingThreshold.outputEqualizer4: false,
      SettingThreshold.outputEqualizer5: false,
      SettingThreshold.outputEqualizer6: false,
      SettingControl.forwardInputAttenuation1: true,
      SettingControl.forwardInputAttenuation2: false,
      SettingControl.forwardInputAttenuation3: false,
      SettingControl.forwardInputAttenuation4: false,
      SettingControl.forwardInputAttenuation5: false,
      SettingControl.forwardInputAttenuation6: false,
      SettingControl.forwardInputEqualizer1: true,
      SettingControl.forwardInputEqualizer2: false,
      SettingControl.forwardInputEqualizer3: false,
      SettingControl.forwardInputEqualizer4: false,
      SettingControl.forwardInputEqualizer5: false,
      SettingControl.forwardInputEqualizer6: false,
      SettingControl.forwardOutputAttenuation2And3: true,
      SettingControl.forwardOutputAttenuation3And4: false,
      SettingControl.forwardOutputAttenuation5And6: false,
      SettingControl.forwardOutputEqualizer2And3: true,
      SettingControl.forwardOutputEqualizer3And4: false,
      SettingControl.forwardOutputEqualizer5And6: true,
      SettingControl.returnOutputAttenuation1: true,
      SettingControl.returnOutputEqualizer1: true,
      SettingControl.returnInputAttenuation1: false,
      SettingControl.returnInputAttenuation2: false,
      SettingControl.returnInputAttenuation3: false,
      SettingControl.returnInputAttenuation4: false,
      SettingControl.returnInputAttenuation5: false,
      SettingControl.returnInputAttenuation6: false,
      SettingControl.returnInputAttenuation2And3: true,
      SettingControl.returnInputAttenuation5And6: true,
      SettingControl.returnIngressSetting1: false,
      SettingControl.returnIngressSetting2: false,
      SettingControl.returnIngressSetting3: false,
      SettingControl.returnIngressSetting4: false,
      SettingControl.returnIngressSetting5: false,
      SettingControl.returnIngressSetting6: false,
      SettingControl.returnIngressSetting2And3: true,
      SettingControl.returnIngressSetting5And6: true,
    },
    '7': {
      // C-Cor LE
      SettingConfiruration.location: true,
      SettingConfiruration.coordinates: true,
      SettingConfiruration.splitOptions: true,
      SettingConfiruration.pilotFrequencySelect: true,
      SettingConfiruration.startFrequency: true,
      SettingConfiruration.stopFrequency: true,
      SettingConfiruration.pilot1: true,
      SettingConfiruration.pilot2: true,
      SettingConfiruration.agcMode: true,
      SettingConfiruration.alcMode: true,
      SettingConfiruration.logInterval: true,
      SettingConfiruration.rfOutputLogInterval: true,
      SettingConfiruration.cableLength: true,
      SettingThreshold.workingMode: true,
      SettingThreshold.splitOptions: true,
      SettingThreshold.temperature: true,
      SettingThreshold.inputVoltage24V: true,
      SettingThreshold.inputVoltage8V: false,
      SettingThreshold.inputVoltage5p2V: false,
      SettingThreshold.inputVoltage3p3V: false,
      SettingThreshold.inputVoltageRipple24V: true,
      SettingThreshold.inputPower1p8G: true,
      SettingThreshold.outputPower: true,
      SettingThreshold.outputPower1: false,
      SettingThreshold.outputPower2: false,
      SettingThreshold.outputPower3: false,
      SettingThreshold.outputPower4: false,
      SettingThreshold.outputPower5: false,
      SettingThreshold.outputPower6: false,
      SettingThreshold.pilot1Status: true,
      SettingThreshold.pilot2Status: true,
      SettingThreshold.startFrequencyOutputLevel: true,
      SettingThreshold.stopFrequencyOutputLevel: true,
      SettingThreshold.operatingSlope: false,
      SettingThreshold.outputAttenuation1: false,
      SettingThreshold.outputAttenuation2: false,
      SettingThreshold.outputAttenuation3: false,
      SettingThreshold.outputAttenuation4: false,
      SettingThreshold.outputAttenuation5: false,
      SettingThreshold.outputAttenuation6: false,
      SettingThreshold.outputEqualizer1: false,
      SettingThreshold.outputEqualizer2: false,
      SettingThreshold.outputEqualizer3: false,
      SettingThreshold.outputEqualizer4: false,
      SettingThreshold.outputEqualizer5: false,
      SettingThreshold.outputEqualizer6: false,
      SettingControl.forwardInputAttenuation1: true,
      SettingControl.forwardInputAttenuation2: false,
      SettingControl.forwardInputAttenuation3: false,
      SettingControl.forwardInputAttenuation4: false,
      SettingControl.forwardInputAttenuation5: false,
      SettingControl.forwardInputAttenuation6: false,
      SettingControl.forwardInputEqualizer1: true,
      SettingControl.forwardInputEqualizer2: false,
      SettingControl.forwardInputEqualizer3: false,
      SettingControl.forwardInputEqualizer4: false,
      SettingControl.forwardInputEqualizer5: false,
      SettingControl.forwardInputEqualizer6: false,
      SettingControl.forwardOutputAttenuation2And3: false,
      SettingControl.forwardOutputAttenuation3And4: false,
      SettingControl.forwardOutputAttenuation5And6: false,
      SettingControl.forwardOutputEqualizer2And3: false,
      SettingControl.forwardOutputEqualizer3And4: false,
      SettingControl.forwardOutputEqualizer5And6: false,
      SettingControl.returnOutputAttenuation1: true,
      SettingControl.returnOutputEqualizer1: true,
      SettingControl.returnInputAttenuation1: false,
      SettingControl.returnInputAttenuation2: true,
      SettingControl.returnInputAttenuation3: false,
      SettingControl.returnInputAttenuation4: false,
      SettingControl.returnInputAttenuation5: false,
      SettingControl.returnInputAttenuation6: false,
      SettingControl.returnInputAttenuation2And3: false,
      SettingControl.returnInputAttenuation5And6: false,
      SettingControl.returnIngressSetting1: false,
      SettingControl.returnIngressSetting2: true,
      SettingControl.returnIngressSetting3: false,
      SettingControl.returnIngressSetting4: false,
      SettingControl.returnIngressSetting5: false,
      SettingControl.returnIngressSetting6: false,
      SettingControl.returnIngressSetting2And3: false,
      SettingControl.returnIngressSetting5And6: false,
    },
  };

  static Map<String, List<Map<Enum, DataKey>>> controlItemDataMapCollection = {
    '1': [
      // SDLE
      {
        SettingControl.forwardInputAttenuation1: DataKey.dsVVA1,
        SettingControl.forwardInputEqualizer1: DataKey.dsSlope1,
      },
      {
        SettingControl.returnOutputAttenuation1: DataKey.usVCA2,
        SettingControl.returnOutputEqualizer1: DataKey.eREQ,
        SettingControl.returnInputAttenuation2: DataKey.usVCA1,
        SettingControl.returnIngressSetting2: DataKey.ingressSetting2,
      }
    ],
    '2': [
      // Moto BLE
      {
        SettingControl.forwardInputAttenuation1: DataKey.dsVVA1,
        SettingControl.forwardInputEqualizer1: DataKey.dsSlope1,
      },
      {
        SettingControl.returnOutputAttenuation1: DataKey.usVCA2,
        SettingControl.returnOutputEqualizer1: DataKey.eREQ,
        SettingControl.returnInputAttenuation2: DataKey.usVCA1,
        SettingControl.returnIngressSetting2: DataKey.ingressSetting2,
      }
    ],
    '3': [
      // Moto MB
      {
        SettingControl.forwardInputAttenuation1: DataKey.dsVVA1,
        SettingControl.forwardInputEqualizer1: DataKey.dsSlope1,
        SettingControl.forwardOutputAttenuation3And4: DataKey.dsVVA4,
      },
      {
        SettingControl.returnOutputAttenuation1: DataKey.usVCA2,
        SettingControl.returnOutputEqualizer1: DataKey.eREQ,
        SettingControl.returnInputAttenuation2: DataKey.usVCA1,
        SettingControl.returnInputAttenuation3: DataKey.usVCA3,
        SettingControl.returnInputAttenuation4: DataKey.usVCA4,
        SettingControl.returnIngressSetting2: DataKey.ingressSetting2,
        SettingControl.returnIngressSetting3: DataKey.ingressSetting3,
        SettingControl.returnIngressSetting4: DataKey.ingressSetting4,
      },
    ],
    '4': [
      // C-Cor Node
      {
        SettingControl.forwardInputAttenuation1: DataKey.dsVVA1,
        SettingControl.forwardInputAttenuation3: DataKey.dsVVA3,
        SettingControl.forwardInputAttenuation4: DataKey.dsVVA4,
        SettingControl.forwardInputAttenuation6: DataKey.dsVVA6,
        SettingControl.forwardInputEqualizer1: DataKey.dsInSlope1,
        SettingControl.forwardInputEqualizer3: DataKey.dsInSlope3,
        SettingControl.forwardInputEqualizer4: DataKey.dsInSlope4,
        SettingControl.forwardInputEqualizer6: DataKey.dsInSlope6,
      },
      {
        SettingControl.returnInputAttenuation1: DataKey.usVCA1,
        SettingControl.returnInputAttenuation3: DataKey.usVCA3,
        SettingControl.returnInputAttenuation4: DataKey.usVCA4,
        SettingControl.returnInputAttenuation6: DataKey.usVCA6,
        SettingControl.returnIngressSetting1: DataKey.ingressSetting1,
        SettingControl.returnIngressSetting3: DataKey.ingressSetting3,
        SettingControl.returnIngressSetting4: DataKey.ingressSetting4,
        SettingControl.returnIngressSetting6: DataKey.ingressSetting6,
      },
    ],
    '5': [
      {
        // C-Cor TR
        SettingControl.forwardInputAttenuation1: DataKey.dsVVA1,
        SettingControl.forwardInputEqualizer1: DataKey.dsSlope1,
        SettingControl.forwardOutputAttenuation2And3: DataKey.dsVVA4,
        SettingControl.forwardOutputAttenuation5And6: DataKey.dsVVA5,
        SettingControl.forwardOutputEqualizer2And3: DataKey.dsSlope3,
        SettingControl.forwardOutputEqualizer5And6: DataKey.dsSlope4,
      },
      {
        SettingControl.returnOutputAttenuation1: DataKey.usVCA2,
        SettingControl.returnOutputEqualizer1: DataKey.eREQ,
        SettingControl.returnInputAttenuation4: DataKey.usVCA1,
        SettingControl.returnInputAttenuation2And3: DataKey.usVCA3,
        SettingControl.returnInputAttenuation5And6: DataKey.usVCA4,
        SettingControl.returnIngressSetting4: DataKey.ingressSetting2,
        SettingControl.returnIngressSetting2And3: DataKey.ingressSetting3,
        SettingControl.returnIngressSetting5And6: DataKey.ingressSetting4,
      }
    ],
    '6': [
      {
        // C-Cor BR
        SettingControl.forwardInputAttenuation1: DataKey.dsVVA1,
        SettingControl.forwardInputEqualizer1: DataKey.dsSlope1,
        SettingControl.forwardOutputAttenuation2And3: DataKey.dsVVA4,
        SettingControl.forwardOutputAttenuation5And6: DataKey.dsVVA5,
        SettingControl.forwardOutputEqualizer2And3: DataKey.dsSlope3,
        SettingControl.forwardOutputEqualizer5And6: DataKey.dsSlope4,
      },
      {
        SettingControl.returnOutputAttenuation1: DataKey.usVCA2,
        SettingControl.returnOutputEqualizer1: DataKey.eREQ,
        SettingControl.returnInputAttenuation2And3: DataKey.usVCA3,
        SettingControl.returnInputAttenuation5And6: DataKey.usVCA4,
        SettingControl.returnIngressSetting2And3: DataKey.ingressSetting3,
        SettingControl.returnIngressSetting5And6: DataKey.ingressSetting4,
      }
    ],
    '7': [
      {
        // C-Cor LE
        SettingControl.forwardInputAttenuation1: DataKey.dsVVA1,
        SettingControl.forwardInputEqualizer1: DataKey.dsSlope1,
      },
      {
        SettingControl.returnOutputAttenuation1: DataKey.usVCA2,
        SettingControl.returnOutputEqualizer1: DataKey.eREQ,
        SettingControl.returnInputAttenuation2: DataKey.usVCA1,
        SettingControl.returnIngressSetting2: DataKey.ingressSetting2,
      }
    ],
  };
}
