enum Confiruration {
  location,
  coordinates,
  splitOptions,
  startFrequency,
  stopFrequency,
  pilotFrequencySelect,
  pilot1,
  pilot2,
  agcMode,
  alcMode,
  logInterval,
  cableLength,
}

enum Threshold {
  workingMode,
  splitOptions,
  temperature,
  inputVoltage24V,
  inputVoltage8V,
  inputVoltage5p2V,
  inputVoltage3p3V,
  inputVoltageRipple24V,
  outputPower,
  auxPortOutputPower,
  pilot1Status,
  pilot2Status,
  startFrequencyOutputLevel,
  stopFrequencyOutputLevel,
  operatingSlope,
  inputAttenuation1,
  inputAttenuation2,
  inputAttenuation3,
  inputAttenuation4,
  inputAttenuation5,
  inputAttenuation6,
  inputEqualizer1,
  inputEqualizer2,
  inputEqualizer3,
  inputEqualizer4,
  inputEqualizer5,
  inputEqualizer6,
}

enum Control {
  forwardInputAttenuation,
  forwardInputEqualizer,
  returnInputAttenuation1,
  returnInputAttenuation2,
  returnInputAttenuation3,
  returnInputAttenuation4,
  returnInputAttenuation5,
  returnInputAttenuation6,
  returnInputAttenuation2and3,
  returnInputAttenuation5and6,
  returnOutputAttenuation,
  returnOutputEqualizer,
  returnIngressSetting1,
  returnIngressSetting2,
  returnIngressSetting3,
  returnIngressSetting4,
  returnIngressSetting5,
  returnIngressSetting6,
  returnIngressSetting2_3,
  returnIngressSetting5_6,
}

// 0: MFTJ (預留, app不適用)
// 1: SDLE
// 2: MOTO BLE
// 3: MOTO MB
// 4: C-Cor Node
// 5: C-Cor TR
// 6: C-Cor BR
// 7: C-Cor LE

class SettingItemTable {
  static Map<String, Map<Enum, bool>> itemsMap = {
    '1': {
      Confiruration.location: true,
      Confiruration.coordinates: true,
      Confiruration.splitOptions: true,
      Confiruration.startFrequency: true,
      Confiruration.stopFrequency: true,
      Confiruration.pilotFrequencySelect: true,
      Confiruration.pilot1: true,
      Confiruration.pilot2: true,
      Confiruration.agcMode: true,
      Confiruration.alcMode: true,
      Confiruration.logInterval: true,
      Confiruration.cableLength: true,
      Threshold.workingMode: true,
      Threshold.splitOptions: true,
      Threshold.temperature: true,
      Threshold.inputVoltage24V: true,
      Threshold.inputVoltage8V: false,
      Threshold.inputVoltage5p2V: false,
      Threshold.inputVoltage3p3V: false,
      Threshold.inputVoltageRipple24V: true,
      Threshold.outputPower: true,
      Threshold.auxPortOutputPower: false,
      Threshold.pilot1Status: true,
      Threshold.pilot2Status: true,
      Threshold.startFrequencyOutputLevel: true,
      Threshold.stopFrequencyOutputLevel: true,
      Threshold.operatingSlope: true,
      Threshold.inputAttenuation1: false,
      Threshold.inputAttenuation2: false,
      Threshold.inputAttenuation3: false,
      Threshold.inputAttenuation4: false,
      Threshold.inputAttenuation5: false,
      Threshold.inputAttenuation6: false,
      Threshold.inputEqualizer1: false,
      Threshold.inputEqualizer2: false,
      Threshold.inputEqualizer3: false,
      Threshold.inputEqualizer4: false,
      Threshold.inputEqualizer5: false,
      Threshold.inputEqualizer6: false,
      Control.forwardInputAttenuation: true,
      Control.forwardInputEqualizer: false,
      Control.returnInputAttenuation1: false,
      Control.returnInputAttenuation2: true,
      Control.returnInputAttenuation3: false,
      Control.returnInputAttenuation4: false,
      Control.returnInputAttenuation5: false,
      Control.returnInputAttenuation6: false,
      Control.returnInputAttenuation2and3: false,
      Control.returnInputAttenuation5and6: false,
      Control.returnOutputAttenuation: true,
      Control.returnOutputEqualizer: true,
      Control.returnIngressSetting1: false,
      Control.returnIngressSetting2: true,
      Control.returnIngressSetting3: false,
      Control.returnIngressSetting4: false,
      Control.returnIngressSetting5: false,
      Control.returnIngressSetting6: false,
      Control.returnIngressSetting2_3: false,
      Control.returnIngressSetting5_6: false,
    },
    '2': {
      Confiruration.location: true,
      Confiruration.coordinates: true,
      Confiruration.splitOptions: true,
      Confiruration.startFrequency: true,
      Confiruration.stopFrequency: true,
      Confiruration.pilotFrequencySelect: true,
      Confiruration.pilot1: true,
      Confiruration.pilot2: true,
      Confiruration.agcMode: true,
      Confiruration.alcMode: true,
      Confiruration.logInterval: true,
      Confiruration.cableLength: true,
      Threshold.workingMode: true,
      Threshold.splitOptions: true,
      Threshold.temperature: true,
      Threshold.inputVoltage24V: true,
      Threshold.inputVoltage8V: false,
      Threshold.inputVoltage5p2V: false,
      Threshold.inputVoltage3p3V: false,
      Threshold.inputVoltageRipple24V: true,
      Threshold.outputPower: true,
      Threshold.auxPortOutputPower: false,
      Threshold.pilot1Status: true,
      Threshold.pilot2Status: true,
      Threshold.startFrequencyOutputLevel: true,
      Threshold.stopFrequencyOutputLevel: true,
      Threshold.operatingSlope: true,
      Threshold.inputAttenuation1: false,
      Threshold.inputAttenuation2: false,
      Threshold.inputAttenuation3: false,
      Threshold.inputAttenuation4: false,
      Threshold.inputAttenuation5: false,
      Threshold.inputAttenuation6: false,
      Threshold.inputEqualizer1: false,
      Threshold.inputEqualizer2: false,
      Threshold.inputEqualizer3: false,
      Threshold.inputEqualizer4: false,
      Threshold.inputEqualizer5: false,
      Threshold.inputEqualizer6: false,
      Control.forwardInputAttenuation: true,
      Control.forwardInputEqualizer: false,
      Control.returnInputAttenuation1: false,
      Control.returnInputAttenuation2: true,
      Control.returnInputAttenuation3: false,
      Control.returnInputAttenuation4: false,
      Control.returnInputAttenuation5: false,
      Control.returnInputAttenuation6: false,
      Control.returnInputAttenuation2and3: false,
      Control.returnInputAttenuation5and6: false,
      Control.returnOutputAttenuation: true,
      Control.returnOutputEqualizer: true,
      Control.returnIngressSetting1: false,
      Control.returnIngressSetting2: true,
      Control.returnIngressSetting3: false,
      Control.returnIngressSetting4: false,
      Control.returnIngressSetting5: false,
      Control.returnIngressSetting6: false,
      Control.returnIngressSetting2_3: false,
      Control.returnIngressSetting5_6: false,
    },
    '3': {
      Confiruration.location: true,
      Confiruration.coordinates: true,
      Confiruration.splitOptions: true,
      Confiruration.startFrequency: true,
      Confiruration.stopFrequency: true,
      Confiruration.pilotFrequencySelect: true,
      Confiruration.pilot1: true,
      Confiruration.pilot2: true,
      Confiruration.agcMode: true,
      Confiruration.alcMode: true,
      Confiruration.logInterval: true,
      Confiruration.cableLength: true,
      Threshold.workingMode: true,
      Threshold.splitOptions: true,
      Threshold.temperature: true,
      Threshold.inputVoltage24V: true,
      Threshold.inputVoltage8V: false,
      Threshold.inputVoltage5p2V: false,
      Threshold.inputVoltage3p3V: false,
      Threshold.inputVoltageRipple24V: true,
      Threshold.outputPower: true,
      Threshold.auxPortOutputPower: false,
      Threshold.pilot1Status: true,
      Threshold.pilot2Status: true,
      Threshold.startFrequencyOutputLevel: true,
      Threshold.stopFrequencyOutputLevel: true,
      Threshold.operatingSlope: true,
      Threshold.inputAttenuation1: false,
      Threshold.inputAttenuation2: false,
      Threshold.inputAttenuation3: false,
      Threshold.inputAttenuation4: false,
      Threshold.inputAttenuation5: false,
      Threshold.inputAttenuation6: false,
      Threshold.inputEqualizer1: false,
      Threshold.inputEqualizer2: false,
      Threshold.inputEqualizer3: false,
      Threshold.inputEqualizer4: false,
      Threshold.inputEqualizer5: false,
      Threshold.inputEqualizer6: false,
      Control.forwardInputAttenuation: true,
      Control.forwardInputEqualizer: true,
      Control.returnInputAttenuation1: false,
      Control.returnInputAttenuation2: true,
      Control.returnInputAttenuation3: true,
      Control.returnInputAttenuation4: true,
      Control.returnInputAttenuation5: false,
      Control.returnInputAttenuation6: false,
      Control.returnInputAttenuation2and3: false,
      Control.returnInputAttenuation5and6: false,
      Control.returnOutputAttenuation: true,
      Control.returnOutputEqualizer: true,
      Control.returnIngressSetting1: false,
      Control.returnIngressSetting2: true,
      Control.returnIngressSetting3: true,
      Control.returnIngressSetting4: true,
      Control.returnIngressSetting5: false,
      Control.returnIngressSetting6: false,
      Control.returnIngressSetting2_3: false,
      Control.returnIngressSetting5_6: false,
    },
    '4': {
      Confiruration.location: true,
      Confiruration.coordinates: true,
      Confiruration.splitOptions: true,
      Confiruration.startFrequency: false,
      Confiruration.stopFrequency: false,
      Confiruration.pilotFrequencySelect: false,
      Confiruration.pilot1: false,
      Confiruration.pilot2: false,
      Confiruration.agcMode: false,
      Confiruration.alcMode: false,
      Confiruration.logInterval: true,
      Confiruration.cableLength: false,
      Threshold.workingMode: false,
      Threshold.splitOptions: true,
      Threshold.temperature: true,
      Threshold.inputVoltage24V: true,
      Threshold.inputVoltage8V: false,
      Threshold.inputVoltage5p2V: false,
      Threshold.inputVoltage3p3V: false,
      Threshold.inputVoltageRipple24V: false,
      Threshold.outputPower: true,
      Threshold.auxPortOutputPower: false,
      Threshold.pilot1Status: false,
      Threshold.pilot2Status: false,
      Threshold.startFrequencyOutputLevel: false,
      Threshold.stopFrequencyOutputLevel: false,
      Threshold.operatingSlope: false,
      Threshold.inputAttenuation1: true,
      Threshold.inputAttenuation2: false,
      Threshold.inputAttenuation3: true,
      Threshold.inputAttenuation4: true,
      Threshold.inputAttenuation5: false,
      Threshold.inputAttenuation6: true,
      Threshold.inputEqualizer1: true,
      Threshold.inputEqualizer2: false,
      Threshold.inputEqualizer3: true,
      Threshold.inputEqualizer4: true,
      Threshold.inputEqualizer5: false,
      Threshold.inputEqualizer6: true,
      Control.forwardInputAttenuation: false,
      Control.forwardInputEqualizer: false,
      Control.returnInputAttenuation1: true,
      Control.returnInputAttenuation2: false,
      Control.returnInputAttenuation3: true,
      Control.returnInputAttenuation4: true,
      Control.returnInputAttenuation5: false,
      Control.returnInputAttenuation6: true,
      Control.returnInputAttenuation2and3: false,
      Control.returnInputAttenuation5and6: false,
      Control.returnOutputAttenuation: false,
      Control.returnOutputEqualizer: false,
      Control.returnIngressSetting1: true,
      Control.returnIngressSetting2: false,
      Control.returnIngressSetting3: true,
      Control.returnIngressSetting4: true,
      Control.returnIngressSetting5: false,
      Control.returnIngressSetting6: true,
      Control.returnIngressSetting2_3: false,
      Control.returnIngressSetting5_6: false,
    },
    '5': {
      Confiruration.location: true,
      Confiruration.coordinates: true,
      Confiruration.splitOptions: true,
      Confiruration.startFrequency: true,
      Confiruration.stopFrequency: true,
      Confiruration.pilotFrequencySelect: true,
      Confiruration.pilot1: true,
      Confiruration.pilot2: true,
      Confiruration.agcMode: true,
      Confiruration.alcMode: true,
      Confiruration.logInterval: true,
      Confiruration.cableLength: true,
      Threshold.workingMode: true,
      Threshold.splitOptions: true,
      Threshold.temperature: true,
      Threshold.inputVoltage24V: true,
      Threshold.inputVoltage8V: false,
      Threshold.inputVoltage5p2V: false,
      Threshold.inputVoltage3p3V: false,
      Threshold.inputVoltageRipple24V: true,
      Threshold.outputPower: true,
      Threshold.auxPortOutputPower: true,
      Threshold.pilot1Status: true,
      Threshold.pilot2Status: true,
      Threshold.startFrequencyOutputLevel: true,
      Threshold.stopFrequencyOutputLevel: true,
      Threshold.operatingSlope: true,
      Threshold.inputAttenuation1: false,
      Threshold.inputAttenuation2: false,
      Threshold.inputAttenuation3: false,
      Threshold.inputAttenuation4: false,
      Threshold.inputAttenuation5: false,
      Threshold.inputAttenuation6: false,
      Threshold.inputEqualizer1: false,
      Threshold.inputEqualizer2: false,
      Threshold.inputEqualizer3: false,
      Threshold.inputEqualizer4: false,
      Threshold.inputEqualizer5: false,
      Threshold.inputEqualizer6: false,
      Control.forwardInputAttenuation: true,
      Control.forwardInputEqualizer: true,
      Control.returnInputAttenuation1: false,
      Control.returnInputAttenuation2: false,
      Control.returnInputAttenuation3: false,
      Control.returnInputAttenuation4: true,
      Control.returnInputAttenuation5: false,
      Control.returnInputAttenuation6: false,
      Control.returnInputAttenuation2and3: true,
      Control.returnInputAttenuation5and6: true,
      Control.returnOutputAttenuation: true,
      Control.returnOutputEqualizer: true,
      Control.returnIngressSetting1: false,
      Control.returnIngressSetting2: false,
      Control.returnIngressSetting3: false,
      Control.returnIngressSetting4: true,
      Control.returnIngressSetting5: false,
      Control.returnIngressSetting6: false,
      Control.returnIngressSetting2_3: true,
      Control.returnIngressSetting5_6: true,
    },
    '6': {
      Confiruration.location: true,
      Confiruration.coordinates: true,
      Confiruration.splitOptions: true,
      Confiruration.startFrequency: true,
      Confiruration.stopFrequency: true,
      Confiruration.pilotFrequencySelect: true,
      Confiruration.pilot1: true,
      Confiruration.pilot2: true,
      Confiruration.agcMode: true,
      Confiruration.alcMode: true,
      Confiruration.logInterval: true,
      Confiruration.cableLength: true,
      Threshold.workingMode: true,
      Threshold.splitOptions: true,
      Threshold.temperature: true,
      Threshold.inputVoltage24V: true,
      Threshold.inputVoltage8V: false,
      Threshold.inputVoltage5p2V: false,
      Threshold.inputVoltage3p3V: false,
      Threshold.inputVoltageRipple24V: true,
      Threshold.outputPower: true,
      Threshold.auxPortOutputPower: false,
      Threshold.pilot1Status: true,
      Threshold.pilot2Status: true,
      Threshold.startFrequencyOutputLevel: true,
      Threshold.stopFrequencyOutputLevel: true,
      Threshold.operatingSlope: true,
      Threshold.inputAttenuation1: false,
      Threshold.inputAttenuation2: false,
      Threshold.inputAttenuation3: false,
      Threshold.inputAttenuation4: false,
      Threshold.inputAttenuation5: false,
      Threshold.inputAttenuation6: false,
      Threshold.inputEqualizer1: false,
      Threshold.inputEqualizer2: false,
      Threshold.inputEqualizer3: false,
      Threshold.inputEqualizer4: false,
      Threshold.inputEqualizer5: false,
      Threshold.inputEqualizer6: false,
      Control.forwardInputAttenuation: true,
      Control.forwardInputEqualizer: true,
      Control.returnInputAttenuation1: false,
      Control.returnInputAttenuation2: false,
      Control.returnInputAttenuation3: false,
      Control.returnInputAttenuation4: false,
      Control.returnInputAttenuation5: false,
      Control.returnInputAttenuation6: false,
      Control.returnInputAttenuation2and3: true,
      Control.returnInputAttenuation5and6: true,
      Control.returnOutputAttenuation: true,
      Control.returnOutputEqualizer: true,
      Control.returnIngressSetting1: false,
      Control.returnIngressSetting2: false,
      Control.returnIngressSetting3: false,
      Control.returnIngressSetting4: false,
      Control.returnIngressSetting5: false,
      Control.returnIngressSetting6: false,
      Control.returnIngressSetting2_3: true,
      Control.returnIngressSetting5_6: true,
    },
    '7': {
      Confiruration.location: true,
      Confiruration.coordinates: true,
      Confiruration.splitOptions: true,
      Confiruration.startFrequency: true,
      Confiruration.stopFrequency: true,
      Confiruration.pilotFrequencySelect: true,
      Confiruration.pilot1: true,
      Confiruration.pilot2: true,
      Confiruration.agcMode: true,
      Confiruration.alcMode: true,
      Confiruration.logInterval: true,
      Confiruration.cableLength: true,
      Threshold.workingMode: true,
      Threshold.splitOptions: true,
      Threshold.temperature: true,
      Threshold.inputVoltage24V: true,
      Threshold.inputVoltage8V: false,
      Threshold.inputVoltage5p2V: false,
      Threshold.inputVoltage3p3V: false,
      Threshold.inputVoltageRipple24V: true,
      Threshold.outputPower: true,
      Threshold.auxPortOutputPower: false,
      Threshold.pilot1Status: true,
      Threshold.pilot2Status: true,
      Threshold.startFrequencyOutputLevel: true,
      Threshold.stopFrequencyOutputLevel: true,
      Threshold.operatingSlope: true,
      Threshold.inputAttenuation1: false,
      Threshold.inputAttenuation2: false,
      Threshold.inputAttenuation3: false,
      Threshold.inputAttenuation4: false,
      Threshold.inputAttenuation5: false,
      Threshold.inputAttenuation6: false,
      Threshold.inputEqualizer1: false,
      Threshold.inputEqualizer2: false,
      Threshold.inputEqualizer3: false,
      Threshold.inputEqualizer4: false,
      Threshold.inputEqualizer5: false,
      Threshold.inputEqualizer6: false,
      Control.forwardInputAttenuation: true,
      Control.forwardInputEqualizer: false,
      Control.returnInputAttenuation1: false,
      Control.returnInputAttenuation2: true,
      Control.returnInputAttenuation3: false,
      Control.returnInputAttenuation4: false,
      Control.returnInputAttenuation5: false,
      Control.returnInputAttenuation6: false,
      Control.returnInputAttenuation2and3: false,
      Control.returnInputAttenuation5and6: false,
      Control.returnOutputAttenuation: true,
      Control.returnOutputEqualizer: true,
      Control.returnIngressSetting1: false,
      Control.returnIngressSetting2: true,
      Control.returnIngressSetting3: false,
      Control.returnIngressSetting4: false,
      Control.returnIngressSetting5: false,
      Control.returnIngressSetting6: false,
      Control.returnIngressSetting2_3: false,
      Control.returnIngressSetting5_6: false,
    },
  };
}
